"""init migration

Revision ID: b114d590deee
Revises: 
Create Date: 2024-05-06 02:56:04.581586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b114d590deee'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ltmoldinventory',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('rfidno', sa.String(length=255), nullable=False),
    sa.Column('finalinventory', sa.Integer(), nullable=False),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('no')
    )
    op.create_table('ltmoldmap',
    sa.Column('no', sa.Integer(), nullable=False),
    sa.Column('moldno', sa.String(length=255), nullable=True),
    sa.Column('rfidno', sa.String(length=255), nullable=True),
    sa.Column('memo', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('no')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ltmoldmap')
    op.drop_table('ltmoldinventory')
    # ### end Alembic commands ###
