FROM node:19-alpine AS builder
ENV NODE_ENV production
ARG REACT_APP_API_HOST
ARG REACT_APP_API_PORT
ENV VITE_API_HOST=${REACT_APP_API_HOST}
ENV VITE_API_PORT=${REACT_APP_API_PORT}
ENV REACT_APP_API_HOST=${REACT_APP_API_HOST}
ENV REACT_APP_API_PORT=${REACT_APP_API_PORT}
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
COPY package-lock.json .
RUN npm ci --only=production=false
# Copy app files
COPY . .
# Build the app
RUN npm run build

# Bundle static assets with nginx
FROM nginx:1.24-alpine as production
ENV NODE_ENV production
RUN rm -rf /usr/share/nginx/html/*
# Copy built assets from builder
COPY --from=builder /app/build /usr/share/nginx/html
# Add nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Expose port
EXPOSE 80
# Start nginx
CMD ["nginx", "-g", "daemon off;"]
