services:
  db:
    image: mariadb:10-focal
    command: "--default-authentication-plugin=mysql_native_password"
    restart: always
    healthcheck:
      # test: ['CMD-SHELL', 'mysqladmin ping -h 127.0.0.1 --password="$$(cat /run/secrets/db-password)" --silent']
      test:
        [
          "CMD-SHELL",
          "mysqladmin ping -h 127.0.0.1 --password=${DB_PASSWORD} --silent",
        ]
      interval: 3s
      retries: 5
      start_period: 30s
    # secrets: MinGW cannot accept this
    #   - db-password
    volumes:
      - db-data:/var/lib/mysql
    networks:
      - backnet
    environment:
      # - MYSQL_ROOT_PASSWORD_FILE=/run/secrets/db-password
      - MYSQL_DATABASE=${DB_DATABASE}
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD}
    expose:
      - 3306
      - 33060
    ports:
      - "${DB_PORT:-3306}:3306"

  backend:
    build: backend
    image: gunicorn_flask
    restart: always
    ports:
      - "${FLASK_RUN_PORT}:5000"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:5000/flask-health-check || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    command: sh init.sh
    networks:
      - backnet
      - frontnet
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - LOGLEVEL=${LOGLEVEL}
      # - FLASK_RUN_PORT=${FLASK_RUN_PORT}
      - SECRET_KEY=${SECRET_KEY}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - DATABASE_URL=${DATABASE_URL}
      - MOLD_DATABASE_URL=${MOLD_DATABASE_URL}
      - OPCUA_DATABASE_URL=${OPCUA_DATABASE_URL}
      # MQTT
      - REMOTE=${REMOTE}
      - MQTT_ON=${MQTT_ON}
      - MQTT_BROKER_IP=${MQTT_BROKER_IP:-localhost}
      - MQTT_BROKER_PORT=${MQTT_BROKER_PORT:-1883}
      - MQTT_USER=${MQTT_USER}
      - MQTT_PASSWORD=${MQTT_PASSWORD}
      - MQTT_TOPIC_DATA=${MQTT_TOPIC_DATA}
      - MQTT_TOPIC_COTROL=${MQTT_TOPIC_COTROL}
      # 凌越ERP
      - LY_ERP_ON=${LY_ERP_ON}
      - LY_ERP_URL=${LY_ERP_URL}
      - LY_ERP_PUSID=${LY_ERP_PUSID}
      - LY_ERP_PVERIFYKEY=${LY_ERP_PVERIFYKEY}
      - LY_ERP_ICPNO=${LY_ERP_ICPNO}
      - LY_XML_SOAP_NAMESPACE=${LY_XML_SOAP_NAMESPACE}
      - LY_XML_TEMPURI_NAMESPACE=${LY_XML_TEMPURI_NAMESPACE}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: frontend
      target: production
      args:
        - REACT_APP_API_HOST=${REACT_APP_API_HOST}
        - REACT_APP_API_PORT=${REACT_APP_API_PORT}
        # 凌越ERP
        - REACT_APP_LY_ERP_ON=${LY_ERP_ON}
    # environment:
    #   - REACT_APP_API_HOST=${REACT_APP_API_HOST}
    #   - REACT_APP_API_PORT=${REACT_APP_API_PORT}
    restart: always
    ports:
      - "${REACT_APP_PORT}:80"
    networks:
      - frontnet
    depends_on:
      backend:
        condition: service_healthy

  inventory:
    build: inventory
    restart: always
    ports:
      - "${INVENTORY_RUN_PORT}:5001"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "curl --silent --fail localhost:5001/flask-health-check || exit 1",
        ]
      interval: 10s
      timeout: 10s
      retries: 3
    command: sh init.sh
    volumes:
      - ./inventory/.:/home/app/
    networks:
      - backnet
      - frontnet
    environment:
      - FLASK_APP=${FLASK_APP}
      - FLASK_ENV=${FLASK_ENV}
      - LOGLEVEL=${LOGLEVEL}
      - DATABASE_URL=${DATABASE_URL}
      - ALEMBIC_VERSION_INVENTORY=${ALEMBIC_VERSION_INVENTORY}
    depends_on:
      db:
        condition: service_healthy

volumes:
  db-data:

secrets:
  db-password:
    file: db/password.txt

networks:
  backnet:
  frontnet:
