"""Initial migration.

Revision ID: 9ffbd71a81d4
Revises: 
Create Date: 2023-07-11 11:06:26.873581

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9ffbd71a81d4'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
                    sa.Column('id', sa.Integer(), nullable=False),
                    sa.Column('name', sa.String(length=64), nullable=True),
                    sa.Column('default', sa.Boolean(), nullable=True),
                    sa.Column('permissions', sa.Integer(), nullable=True),
                    sa.Column('description', sa.String(
                        length=50), nullable=True),
                    sa.PrimaryKeyConstraint('id'),
                    sa.UniqueConstraint('name')
                    )
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_roles_default'), [
                              'default'], unique=False)

    user_table = op.create_table('user',
                                 sa.Column('id', sa.Integer(), nullable=False),
                                 sa.Column('email', sa.String(
                                     length=64), nullable=True),
                                 sa.Column('username', sa.String(
                                     length=15), nullable=True),
                                 sa.Column('name', sa.String(
                                     length=64), nullable=True),
                                 sa.Column('password_hash', sa.String(
                                     length=128), nullable=True),
                                 sa.Column('joined_date',
                                           sa.DateTime(), nullable=True),
                                 sa.Column('role_id', sa.Integer(),
                                           nullable=True),
                                 sa.ForeignKeyConstraint(
                                     ['role_id'], ['roles.id'], ),
                                 sa.PrimaryKeyConstraint('id')
                                 )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), [
                              'email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_username'), [
                              'username'], unique=True)

    # ### end Alembic commands ###
    op.bulk_insert(
        user_table,
        [
            {'id': 1, 'email': 'admin@example.com', 'username': 'admin',
                'password_hash': '$2b$12$SmWDMVGMJlF54w7QMweocOSHizJQel/lcrnG9ZC960VtM78cFFk.6', 'joined_date': datetime.utcnow()}
        ]
    )


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_username'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_roles_default'))

    op.drop_table('roles')
    # ### end Alembic commands ###
