"""add acceptable conditions

Revision ID: b3c9c20b7e01
Revises: f191b44180c1
Create Date: 2023-11-17 06:43:45.117247

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b3c9c20b7e01'
down_revision = 'f191b44180c1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_setting', schema=None) as batch_op:
        batch_op.add_column(sa.Column("acceptable_condition",sa.JSON()))

    register_setting_table = sa.Table("register_setting",
                                   sa.MetaData(),
                                   sa.Column("name", sa.String(length=20)),
                                   sa.Column("acceptable_condition", sa.JSON()))
    # acceptable_condition settings
    # op.execute(
    #     register_setting_table.update()
    #     .where(register_setting_table.c.name == "SENSOR_TEMP_1")
    #     .values({"acceptable_condition": ["(-INF,25)","[27,29]"]})
    # ) 
    # ### end Alembic commands ###
    

    #         {'id':'26','name':'SENSOR_TEMP_1','label':'溫度_1','unit':'℃','gateway_id':1,'device_id':4},
    #         {'id':'28','name':'SENSOR_TEMP_2','label':'溫度_2','unit':'℃','gateway_id':1,'device_id':4},
    #         {'id':'31','name':'POWER','label':'開關_1','unit':'','gateway_id':1,'device_id':1},
    #         {'id':'32','name':'POWER','label':'開關_2','unit':'','gateway_id':1,'device_id':1},
    #         {'id':'33','name':'POWER','label':'開關_3','unit':'','gateway_id':1,'device_id':1},
    #         {'id':'34','name':'POWER','label':'開關_4','unit':'','gateway_id':1,'device_id':1},
    #         {'id':'35','name':'POWER','label':'開關','unit':'','gateway_id':1,'device_id':3},
    #         {'id':'63','name':'SENSOR_TEMP_1','label':'溫度_1','unit':'℃','gateway_id':2,'device_id':10},
    #         {'id':'65','name':'SENSOR_TEMP_2','label':'溫度_2','unit':'℃','gateway_id':2,'device_id':10},
    #         {'id':'71','name':'POWER','label':'開關','unit':'','gateway_id':2,'device_id':9},
    #         {'id':'74','name':'POWER','label':'開關','unit':'','gateway_id':2,'device_id':7},
    #         {'id':'80','name':'RPM','label':'轉速','unit':'%','gateway_id':2,'device_id':7},
    #         {'id':'111','name':'SENSOR_TEMP_1','label':'溫度_1','unit':'℃','gateway_id':3,'device_id':16},
    #         {'id':'113','name':'SENSOR_TEMP_2','label':'溫度_2','unit':'℃','gateway_id':3,'device_id':16},
    #         {'id':'119','name':'POWER','label':'開關','unit':'','gateway_id':3,'device_id':15},
    #         {'id':'122','name':'POWER','label':'開關','unit':'','gateway_id':3,'device_id':13},
    #         {'id':'123','name':'RPM','label':'轉速','unit':'%','gateway_id':3,'device_id':13},
    #         {'id':'154','name':'SENSOR_TEMP_1','label':'溫度_1','unit':'℃','gateway_id':4,'device_id':22},
    #         {'id':'156','name':'SENSOR_TEMP_2','label':'溫度_2','unit':'℃','gateway_id':4,'device_id':22},
    #         {'id':'162','name':'POWER','label':'開關','unit':'','gateway_id':4,'device_id':21},
    #         {'id':'165','name':'POWER','label':'開關','unit':'','gateway_id':4,'device_id':19},
    #         {'id':'166','name':'RPM','label':'轉速','unit':'%','gateway_id':4,'device_id':19},
    #         {'id':'197','name':'SENSOR_TEMP_1','label':'溫度_1','unit':'℃','gateway_id':5,'device_id':28},
    #         {'id':'199','name':'SENSOR_TEMP_2','label':'溫度_2','unit':'℃','gateway_id':5,'device_id':28},
    #         {'id':'205','name':'POWER','label':'開關','unit':'','gateway_id':5,'device_id':27},
    #         {'id':'208','name':'POWER','label':'開關','unit':'','gateway_id':5,'device_id':25},
 
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('register_setting', schema=None) as batch_op:
        batch_op.drop_column("acceptable_condition")
        pass

    # ### end Alembic commands ###
