// machineConfig.js

/**
 * 機台配置 (Machine Configuration)
 * areas：區域列表，每個區域包含其機台清單
 */
export const machineConfig = {
  areas: [
    {
      label: "A區", // 區域顯示名稱
      value: "A", // 區域代碼，用於 MUI Select 的唯一標識
      machines: [
        // 機台清單
        {
          id: "A1",
          label: "A1 (850T)",
          value: "A1",
          tonnage: "850T",
          rate: 8300,
        },
        {
          id: "A2",
          label: "A2 (400T)",
          value: "A2",
          tonnage: "400T",
          rate: 5000,
        },
        {
          id: "A3",
          label: "A3 (550T)",
          value: "A3",
          tonnage: "550T",
          rate: 6300,
        },
        {
          id: "A4",
          label: "A4 (350T)",
          value: "A4",
          tonnage: "350T",
          rate: 4200,
        },
        {
          id: "A5",
          label: "A5 (260T)",
          value: "A5",
          tonnage: "260T",
          rate: 3800,
        },
        {
          id: "A6",
          label: "A6 (80T)",
          value: "A6",
          tonnage: "80T",
          rate: 2000,
        },
        {
          id: "A7",
          label: "A7 (125T)",
          value: "A7",
          tonnage: "125T",
          rate: 2400,
        },
        {
          id: "A8",
          label: "A8 (180T)",
          value: "A8",
          tonnage: "180T",
          rate: 2900,
        },
        {
          id: "A9",
          label: "A9 (180T)",
          value: "A9",
          tonnage: "180T",
          rate: 2900,
        },
        {
          id: "A10",
          label: "A10 (200T)",
          value: "A10",
          tonnage: "200T",
          rate: 3200,
        },
      ],
    },
    {
      label: "B區",
      value: "B",
      machines: [
        {
          id: "B1",
          label: "B1 (500T)",
          value: "B1",
          tonnage: "500T",
          rate: 5500,
        },
        {
          id: "B2",
          label: "B2 (450T)",
          value: "B2",
          tonnage: "450T",
          rate: 10000,
        },
        {
          id: "B3",
          label: "B3 (250T)",
          value: "B3",
          tonnage: "250T",
          rate: 6500,
        },
        {
          id: "B4",
          label: "B4 (230T)",
          value: "B4",
          tonnage: "230T",
          rate: 6000,
        },
        {
          id: "B5",
          label: "B5 (230T)",
          value: "B5",
          tonnage: "230T",
          rate: 6000,
        },
        {
          id: "B6",
          label: "B6 (230T)",
          value: "B6",
          tonnage: "230T",
          rate: 6000,
        },
        {
          id: "B7",
          label: "B7 (230T)",
          value: "B7",
          tonnage: "230T",
          rate: 6000,
        },
        {
          id: "B8",
          label: "B8 (230T)",
          value: "B8",
          tonnage: "230T",
          rate: 6000,
        },
        {
          id: "B9",
          label: "B9 (230T)",
          value: "B9",
          tonnage: "230T",
          rate: 6000,
        },
        {
          id: "B10",
          label: "B10 (230T)",
          value: "B10",
          tonnage: "230T",
          rate: 6000,
        },
        {
          id: "B11",
          label: "B11 (180T)",
          value: "B11",
          tonnage: "180T",
          rate: 3000,
        },
      ],
    },
    {
      label: "C區",
      value: "C",
      machines: [
        {
          id: "C1",
          label: "C1 (550T)",
          value: "C1",
          tonnage: "550T",
          rate: 12000,
        },
        {
          id: "C2",
          label: "C2 (450T)",
          value: "C2",
          tonnage: "450T",
          rate: 5000,
        },
        {
          id: "C3",
          label: "C3 (350T)",
          value: "C3",
          tonnage: "350T",
          rate: 4200,
        },
        {
          id: "C4",
          label: "C4 (400T)",
          value: "C4",
          tonnage: "400T",
          rate: 5000,
        },
        {
          id: "C5",
          label: "C5 (210T)",
          value: "C5",
          tonnage: "210T",
          rate: 3500,
        },
        {
          id: "C6",
          label: "C6 (320T)",
          value: "C6",
          tonnage: "320T",
          rate: 4200,
        },
        {
          id: "C7",
          label: "C7 (320T)",
          value: "C7",
          tonnage: "320T",
          rate: 4200,
        },
        {
          id: "C8",
          label: "C8 (600T)",
          value: "C8",
          tonnage: "600T",
          rate: 6300,
        },
        {
          id: "C9",
          label: "C9 (450T)",
          value: "C9",
          tonnage: "450T",
          rate: 5200,
        },
      ],
    },
    {
      label: "D區",
      value: "D",
      machines: [
        {
          id: "D1",
          label: "D1 (180T)",
          value: "D1",
          tonnage: "180T",
          rate: 2900,
        },
        {
          id: "D2",
          label: "D2 (150T)",
          value: "D2",
          tonnage: "150T",
          rate: 2700,
        },
        {
          id: "D3",
          label: "D3 (140T)",
          value: "D3",
          tonnage: "140T",
          rate: 2700,
        },
        {
          id: "D4",
          label: "D4 (120T)",
          value: "D4",
          tonnage: "120T",
          rate: 2400,
        },
        {
          id: "D5",
          label: "D5 (80T)",
          value: "D5",
          tonnage: "80T",
          rate: 2000,
        },
        {
          id: "D6",
          label: "D6 (450T)",
          value: "D6",
          tonnage: "450T",
          rate: 5500,
        },
      ],
    },
  ],
};
