"""create factory quotation

Revision ID: 0835311ec8f6
Revises: 9aeaf516cfbe
Create Date: 2024-11-14 02:30:10.723642

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0835311ec8f6'
down_revision = '9aeaf516cfbe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ly0000AO_detail',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SD_DATE', sa.DateTime(), nullable=True, comment='貨單日期'),
    sa.Column('SD_NO', sa.String(length=22), nullable=True, comment='貨單編號'),
    sa.Column('SD_SKNO', sa.String(length=30), nullable=True, comment='貨品編號'),
    sa.Column('SD_NAME', sa.String(length=60), nullable=True, comment='品名'),
    sa.Column('SD_PRICE', sa.Float(), nullable=True, comment='單價'),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_ly0000AO_detail_SD_DATE', 'SD_DATE'),
    sa.Index('idx_ly0000AO_detail_SD_SKNO', 'SD_SKNO')
    )

    op.create_table('factoryQuotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotationSN', sa.String(length=255), nullable=True, comment='報價單編號'),
    sa.Column('createDate', sa.TIMESTAMP(), nullable=True, comment='報價單建立日期'),
    sa.Column('customerName', sa.String(length=255), nullable=True, comment='客戶名稱'),
    sa.Column('productSN', sa.String(length=255), nullable=True, comment='產品編號'),
    sa.Column('productName', sa.String(length=255), nullable=True, comment='產品名稱'),
    sa.Column('subtotalCostWithoutOverhead', sa.Float(), nullable=True, comment='成本小計(不含管銷研)'),
    sa.Column('overheadRnd', sa.Float(), nullable=True, comment='管銷研百分比 (short for Overhead & Research and Development Percentage)'),
    sa.Column('profit', sa.Float(), nullable=True, comment='利潤百分比'),
    sa.Column('risk', sa.Float(), nullable=True, comment='風險百分比'),
    sa.Column('annualDiscount', sa.Float(), nullable=True, comment='年降百分比'),
    sa.Column('rebate', sa.Float(), nullable=True, comment='回饋百分比'),
    sa.Column('actualQuotation', sa.Float(), nullable=True, comment='實際報價'),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_factoryQuotation_quotationSN', 'quotationSN'),
    sa.Index('idx_factoryQuotation_createDate', 'createDate'),
    sa.Index('idx_factoryQuotation_customerName', 'customerName'),
    sa.Index('idx_factoryQuotation_productSN', 'productSN'),
    sa.Index('idx_factoryQuotation_productName', 'productName'),
    comment='廠內報價'
    )

    op.create_table('FQProcess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factoryQuotationId', sa.Integer(), nullable=True, comment='對應的報價ID'),
    sa.Column('processOptionId', sa.Integer(), nullable=True, comment='製程選項ID'),
    sa.ForeignKeyConstraint(['processOptionId'], ['processOption.id'], ),
    sa.ForeignKeyConstraint(['factoryQuotationId'], ['factoryQuotation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_FQProcess_factoryQuotationId', 'factoryQuotationId'),
    comment='廠內報價中的製程資訊'
    )

    op.create_table('FQMaterialCostSetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('estimatedDefectRate', sa.Float(), nullable=True, comment='預估不良率 (%)'),
    sa.Column('estimatedMaterialFluctuation', sa.Float(), nullable=True, comment='預估原料波動 (%)'),
    sa.Column('extractionCost', sa.Float(), nullable=True, comment='抽料費用'),
    sa.Column('processingCost', sa.Float(), nullable=True, comment='加工費用'),
    sa.ForeignKeyConstraint(['FQProcessId'], ['FQProcess.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_FQMaterialCostSetting_FQProcessId', 'FQProcessId'),
    comment='廠內報價中的原物料費用計算的參數'
    )

    op.create_table('FQMaterialCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('materialOptionId', sa.Integer(), nullable=True, comment='原物料類別'),
    sa.Column('materialSN', sa.String(length=255), nullable=True, comment='物料編碼'),
    sa.Column('materialName', sa.String(length=255), nullable=True, comment='物料名稱'),
    sa.Column('unit', sa.String(length=255), nullable=True, comment='單位 (如公斤、件等)'),
    sa.Column('weight', sa.Float(), nullable=True, comment='重量'),
    sa.Column('unitPrice', sa.Float(), nullable=True, comment='單價'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['FQProcessId'], ['FQProcess.id'], ),
    sa.ForeignKeyConstraint(['materialOptionId'], ['materialOption.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_FQMaterialCostSetting_FQProcessId', 'FQProcessId'),
    comment='廠內報價中的原物料費用資訊'
    )

    op.create_table('FQPackagingCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('packagingType', sa.String(length=50), nullable=True, comment='包材種類'),
    sa.Column('materialSN', sa.String(length=255), nullable=True, comment='物料編碼'),
    sa.Column('materialName', sa.String(length=255), nullable=True, comment='物料名稱'),
    sa.Column('unit', sa.String(length=255), nullable=True, comment='單位 (如件、公斤等)'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='數量'),
    sa.Column('capacity', sa.Float(), nullable=True, comment='容量'),
    sa.Column('bagsPerKg', sa.Float(), nullable=True, comment='每公斤幾個袋子'),
    sa.Column('unitPrice', sa.Float(), nullable=True, comment='單價'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['FQProcessId'], ['FQProcess.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_FQMaterialCostSetting_FQProcessId', 'FQProcessId'),
    comment='廠內報價中的包材費用資訊'
    )

    op.create_table('FQInjectionMoldingCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('machineId', sa.Integer(), nullable=True, comment='對應的機台ID'),
    sa.Column('workHoursRatio', sa.Float(), nullable=True, comment='工時比例 (%)'),
    sa.Column('defectiveRate', sa.Float(), nullable=True, comment='不良率 (%)'),
    sa.Column('cycleTime', sa.Float(), nullable=True, comment='成型週期 (秒)'),
    sa.Column('packageTime', sa.Float(), nullable=True, comment='灌包工時 (秒)'),
    sa.Column('moldCavity', sa.Integer(), nullable=True, comment='穴數'),
    sa.Column('unitPrice', sa.Float(), nullable=True, comment='單價'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.Column('subTotal', sa.Float(), nullable=True, comment='小計'),
    sa.Column('electricityCost', sa.Float(), nullable=True, comment='電費'),
    sa.ForeignKeyConstraint(['FQProcessId'], ['FQProcess.id'], ),
    sa.ForeignKeyConstraint(['machineId'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_FQMaterialCostSetting_FQProcessId', 'FQProcessId'),
    comment='廠內報價中的成型與生產加工費用資訊'
    )

    op.create_table('FQInPostProcessingCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('workSecond', sa.Float(), nullable=True, comment='工時(秒)'),
    sa.Column('unitPrice', sa.Float(), nullable=True, comment='單價'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['FQProcessId'], ['FQProcess.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_FQMaterialCostSetting_FQProcessId', 'FQProcessId'),
    comment='廠內報價中的廠內後製程與檢驗費用'
    )

    op.create_table('FQOutPostProcessingCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('FQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('unitPrice', sa.Float(), nullable=True, comment='單價'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['FQProcessId'], ['FQProcess.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_FQMaterialCostSetting_FQProcessId', 'FQProcessId'),
    comment='廠內報價中的委外後製程與檢驗費用'
    )

    op.create_table('FQFreight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factoryQuotationId', sa.Integer(), nullable=True, comment='對應的報價ID'),
    sa.Column('deliveryDistance', sa.Float(), nullable=True, comment='送貨距離 (公里)'),
    sa.Column('driverWorkHours', sa.Float(), nullable=True, comment='司機工時'),
    sa.Column('fuelCostPerKM', sa.Float(), nullable=True, comment='油錢單價 (每公里)'),
    sa.Column('estimatedShipment', sa.Integer(), nullable=True, comment='預估出貨數量'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['factoryQuotationId'], ['factoryQuotation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_FQMaterialCostSetting_factoryQuotationId', 'factoryQuotationId'),
    comment='廠內報價中的運費'
    )

    op.create_table('FQCustomsDuty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('factoryQuotationId', sa.Integer(), nullable=True, comment='對應的報價ID'),
    sa.Column('feeType', sa.String(length=255), nullable=True, comment='貨運/關稅'),
    sa.Column('freight', sa.Float(), nullable=True, comment='運費'),
    sa.Column('estimatedShipment', sa.Integer(), nullable=True, comment='預估出貨數量'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['factoryQuotationId'], ['factoryQuotation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_FQMaterialCostSetting_factoryQuotationId', 'factoryQuotationId'),
    comment='廠內報價中的貨運與關稅'
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('FQMaterialCostSetting')
    op.drop_table('FQMaterialCost')
    op.drop_table('FQPackagingCost')
    op.drop_table('FQInjectionMoldingCost')
    op.drop_table('FQInPostProcessingCost')
    op.drop_table('FQOutPostProcessingCost')
    op.drop_table('FQFreight')
    op.drop_table('FQCustomsDuty')
    op.drop_table('FQProcess')
    op.drop_table('factoryQuotation')
    op.drop_table('ly0000AO_detail')
    # ### end Alembic commands ###
