"""create maintenances

Revision ID: 0cdc20b0c74c
Revises: 840e160e1cce
Create Date: 2024-12-16 08:58:36.228582

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '0cdc20b0c74c'
down_revision = '840e160e1cce'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # 機台保養紀錄表
    op.create_table('machineMaintenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('machineId', sa.Integer(), nullable=False, comment='機台ID'),
    sa.Column('year', sa.Integer(), nullable=False, comment='年份'),
    sa.Column('week', sa.Integer(), nullable=False, comment='週次'),
    sa.Column('maintenanceItem', sa.String(length=255), nullable=False, comment='保養檢查項目'),
    sa.Column('inspectionResult', sa.String(length=255), nullable=True, comment='檢查結果。有兩種結果：OK/NG'),
    sa.Column('inspector', sa.String(length=255), nullable=True, comment='檢查者'),
    sa.Column('inspectionDate', sa.TIMESTAMP(), nullable=True, comment='檢查日期'),
    sa.Column('reinspectionResult', sa.String(length=255), nullable=True, comment='複查結果。有兩種結果：OK/NG'),
    sa.Column('reinspector', sa.String(length=255), nullable=True, comment='複查者'),
    sa.Column('reinspectionDate', sa.TIMESTAMP(), nullable=True, comment='複查日期'),
    sa.Column('approver', sa.String(length=255), nullable=True, comment='承認者'),
    sa.Column('approvalDate', sa.TIMESTAMP(), nullable=True, comment='承認日期'),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_machineMaintenance_machineId_year_week', 'machineId', 'year', 'week'),
    )

    # 模具保養紀錄表
    op.create_table('moldMaintenance',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('moldSN', sa.String(length=255), nullable=False, comment='模具編號'),
    sa.Column('year', sa.Integer(), nullable=False, comment='年份'),
    sa.Column('week', sa.Integer(), nullable=False, comment='週次'),
    sa.Column('maintenanceItem', sa.String(length=255), nullable=False, comment='保養檢查項目'),
    sa.Column('inspectionResult', sa.String(length=255), nullable=True, comment='檢查結果。有兩種結果：OK/NG'),
    sa.Column('inspector', sa.String(length=255), nullable=True, comment='檢查者'),
    sa.Column('inspectionDate', sa.TIMESTAMP(), nullable=True, comment='檢查日期'),
    sa.Column('reinspectionResult', sa.String(length=255), nullable=True, comment='複查結果。有兩種結果：OK/NG'),
    sa.Column('reinspector', sa.String(length=255), nullable=True, comment='複查者'),
    sa.Column('reinspectionDate', sa.TIMESTAMP(), nullable=True, comment='複查日期'),
    sa.Column('approver', sa.String(length=255), nullable=True, comment='承認者'),
    sa.Column('approvalDate', sa.TIMESTAMP(), nullable=True, comment='承認日期'),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_machineMaintenance_moldSN_year_week', 'moldSN', 'year', 'week'),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('moldMaintenance')
    op.drop_table('machineMaintenance')
    # ### end Alembic commands ###
