"""create process

Revision ID: 106809a82624
Revises: dc7f1ac1fe8b
Create Date: 2024-08-05 08:50:22.473618

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '106809a82624'
down_revision = 'dc7f1ac1fe8b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('process',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('productId', sa.Integer(), nullable=False),
    sa.Column('processOptionId', sa.Integer(), nullable=False),
    sa.Column('jigSN', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['productId'], ['product.id'], ),
    sa.ForeignKeyConstraint(['processOptionId'], ['processOption.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('process')
    # ### end Alembic commands ###