"""add_foreignkeys_to_ProductionSchedule

Revision ID: 1cf62747091c
Revises: 496e65230508
Create Date: 2024-08-05 09:08:36.760595

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '1cf62747091c'
down_revision = '496e65230508'
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productionSchedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('productId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('processId', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('ltmoldmapId', sa.Integer(), nullable=True))
        batch_op.alter_column('productSN',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('productName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.create_foreign_key('productionSchedule_ibfk_processId', 'process', ['processId'], ['id'])
        batch_op.create_foreign_key('productionSchedule_ibfk_ltmoldmapId', 'ltmoldmap', ['ltmoldmapId'], ['no'])
        batch_op.create_foreign_key('productionSchedule_ibfk_productId', 'product', ['productId'], ['id'])
        batch_op.drop_column('moldNo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productionSchedule', schema=None) as batch_op:
        batch_op.add_column(sa.Column('moldNo', mysql.VARCHAR(length=255), nullable=False))
        batch_op.drop_constraint('productionSchedule_ibfk_processId', type_='foreignkey')
        batch_op.drop_constraint('productionSchedule_ibfk_ltmoldmapId', type_='foreignkey')
        batch_op.drop_constraint('productionSchedule_ibfk_productId', type_='foreignkey')
        batch_op.alter_column('productName',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('productSN',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.drop_column('ltmoldmapId')
        batch_op.drop_column('processId')
        batch_op.drop_column('productId')
    # ### end Alembic commands ###