"""create processMold

Revision ID: 26488421d90f
Revises: 3614f72e7ac8
Create Date: 2024-08-05 08:55:32.487935

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '26488421d90f'
down_revision = '3614f72e7ac8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processMold',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processId', sa.Integer(), nullable=False),
    sa.Column('ltmoldmapId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ltmoldmapId'], ['ltmoldmap.no'], ),
    sa.ForeignKeyConstraint(['processId'], ['process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processMold')
    # ### end Alembic commands ###
