"""create material

Revision ID: 3614f72e7ac8
Revises: 106809a82624
Create Date: 2024-08-05 08:54:28.527050

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3614f72e7ac8'
down_revision = '106809a82624'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('material',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('materialOptionId', sa.Integer(), nullable=True),
    sa.Column('productSN', sa.String(length=255), nullable=False),
    sa.Column('materialSN', sa.String(length=255), nullable=False),
    sa.Column('materialName', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=True),
    sa.Column('unit', sa.String(length=255), nullable=True),
    # the combination of materialSN and productSN should be unique
    sa.UniqueConstraint('productSN', 'materialSN'),
    sa.ForeignKeyConstraint(['materialOptionId'], ['materialOption.id'], ),
    sa.PrimaryKeyConstraint('id'),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('material')
    ### end Alembic commands ###