from alembic import op
import sqlalchemy as sa

#revision identifiers , used by Alenbic 
revision = '38695ced4b88'
down_revision = '9ffbd71a81d4'
branch_labels = None
depends_on = None

def upgrade():
    gateway_setting_table = op.create_table('gateway_setting',
                                        sa.Column('id', sa.Integer(),nullable=False),
                                        sa.Column('type' , sa.String(length = 30),nullable = True),
                                        sa.Column('name', sa.String(length=30), nullable=True),
                                        sa.Column('label', sa.String(length=30), nullable=True),
                                        sa.Column('connect', sa.String(length=30), nullable=True),
                                        sa.Column('port', sa.String(length=5), nullable=True),
                                        sa.Column('enabled', sa.Boolean(), nullable=True),
                                        sa.PrimaryKeyConstraint('id'),
                                        )
    device_setting_table = op.create_table('device_setting',
                                        sa.Column('id' , sa.Integer(), nullable = False),
                                        sa.Column('type', sa.String(length=30), nullable = True),
                                        sa.Column('label', sa.String(length=30) , nullable = True),
                                        sa.Column('name', sa.String(length=30) , nullable = True),
                                        sa.Column('enabled', sa.Boolean(), nullable=True),
                                        sa.PrimaryKeyConstraint('id'),
                                        )
    register_setting_table = op.create_table('register_setting', 
                                            sa.Column('id' , sa.Integer() , nullable= False),
                                            sa.Column('name', sa.String(length=30), nullable = True),
                                            sa.Column('label' , sa.String(length=30) , nullable= False),
                                            sa.Column('unit', sa.String(length=30), nullable = True),
                                            sa.Column('gateway_id' , sa.Integer() , nullable= False),
                                            sa.Column('device_id', sa.Integer(), nullable = True),
                                            sa.Column('modbus_type' , sa.String(length=20) , nullable= False),
                                            sa.Column('length', sa.Integer(), nullable = True),
                                            sa.Column('read_loc' , sa.Integer() , nullable= False),
                                            sa.Column('write_loc', sa.Integer(), nullable = True),
                                            sa.Column('calibration' , sa.String(length=30) , nullable= False),
                                            sa.Column('enabled',  sa.Boolean(), nullable=True),
                                            sa.Column('controllable',  sa.Boolean(), nullable=True),
                                            sa.ForeignKeyConstraint(['gateway_id'],['gateway_setting.id'],),
                                            sa.ForeignKeyConstraint(['device_id'],['device_setting.id'],),
                                            sa.PrimaryKeyConstraint('id'),
                                            )
    
    op.bulk_insert(
        gateway_setting_table,
        [
            {'id': 1, 'type': 'PLC', 'name': 'DORM', 'label':'第14棟' ,'connect': '172.16.0.204', 'port': '503', 'enabled': True },
            {'id': 2, 'type': 'PLC', 'name': 'DORM', 'label':'第4棟' ,'connect': '172.16.0.204', 'port': '503', 'enabled': True },
            {'id': 3, 'type': 'PLC', 'name': 'DORM', 'label':'第2棟' ,'connect': '172.16.0.204', 'port': '503', 'enabled': True },
            
        ]
    )

    op.bulk_insert(
        device_setting_table,
        [
            {'id':1,'type':'FAN','label':'風扇','name':'FAN','enabled':True},
            {'id':2,'type':'COOLING_PAD','label':'水濂系統','name':'COOLING_PAD','enabled':True},
            {'id':3,'type':'METER_ELECTRICTY','label':'電錶','name':'METER_ELECTRICITY','enabled':True},
            {'id':4,'type':'METER_WATER','label':'水錶','name':'METER_WATER','enabled':True},
            {'id':5,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器1','name':'TEMP_HUMI_SENSOR','enabled':True},
            {'id':6,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器2','name':'TEMP_HUMI_SENSOR','enabled':True},
            {'id':7,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器3','name':'TEMP_HUMI_SENSOR','enabled':True},
            {'id':8,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器4','name':'TEMP_HUMI_SENSOR_OUTSIDE','enabled':True},
            {'id':9,'type':'FIELD_SWITCH','label':'盤體開關','name':'FIELD_SWITCH','enabled':True},

            {'id':10,'type':'FAN','label':'風扇','name':'FAN','enabled':True},
            {'id':11,'type':'COOLING_PAD','label':'水濂系統','name':'COOLING_PAD','enabled':True},
            {'id':12,'type':'METER_ELECTRICTY','label':'電錶','name':'METER_ELECTRICITY','enabled':True},
            {'id':13,'type':'METER_WATER','label':'水錶','name':'METER_WATER','enabled':True},
            {'id':14,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器1','name':'TEMP_HUMI_SENSOR','enabled':True},
            {'id':15,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器2','name':'TEMP_HUMI_SENSOR','enabled':True},
            {'id':16,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器3','name':'TEMP_HUMI_SENSOR','enabled':True},
            {'id':17,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器4','name':'TEMP_HUMI_SENSOR_OUTSIDE','enabled':True},
            {'id':18,'type':'FIELD_SWITCH','label':'盤體開關','name':'FIELD_SWITCH','enabled':True},

            {'id':19,'type':'FAN','label':'風扇','name':'FAN','enabled':True},
            {'id':20,'type':'COOLING_PAD','label':'水濂系統','name':'COOLING_PAD','enabled':True},
            {'id':21,'type':'METER_ELECTRICTY','label':'電錶','name':'METER_ELECTRICITY','enabled':True},
            {'id':22,'type':'METER_WATER','label':'水錶','name':'METER_WATER','enabled':True},
            {'id':23,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器1','name':'TEMP_HUMI_SENSOR','enabled':True},
            {'id':24,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器2','name':'TEMP_HUMI_SENSOR','enabled':True},
            {'id':25,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器3','name':'TEMP_HUMI_SENSOR','enabled':True},
            {'id':26,'type':'TEMP_HUMI_SENSOR','label':'溫溼度感測器4','name':'TEMP_HUMI_SENSOR_OUTSIDE','enabled':True},
            {'id':27,'type':'FIELD_SWITCH','label':'盤體開關','name':'FIELD_SWITCH','enabled':True},
        ]
    )


    op.bulk_insert(
        register_setting_table,
        [
            {'id':'1','name':'CURRENT_1','label':'電流_1','unit':'A','gateway_id':1,'device_id':1,'modbus_type':'hr','length':1,'read_loc':341,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'2','name':'CURRENT_2','label':'電流_2','unit':'A','gateway_id':1,'device_id':1,'modbus_type':'hr','length':1,'read_loc':342,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'3','name':'CURRENT_3','label':'電流_3','unit':'A','gateway_id':1,'device_id':1,'modbus_type':'hr','length':1,'read_loc':343,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'4','name':'RPM_SETTING','label':'轉速設定','unit':'%','gateway_id':1,'device_id':1,'modbus_type':'hr','length':2,'read_loc':286,'write_loc':286,'calibration':'IEEE754','enabled':True,'controllable':True,},
            {'id':'5','name':'POWER','label':'開關','unit':'','gateway_id':1,'device_id':1,'modbus_type':'ci','length':1,'read_loc':0,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
            {'id':'6','name':'RPM','label':'轉速','unit':'%','gateway_id':1,'device_id':1,'modbus_type':'hr','length':2,'read_loc':261,'write_loc':None,'calibration':'FAN','enabled':True,'controllable':False,},
            {'id':'7','name':'POWER','label':'開關','unit':'','gateway_id':1,'device_id':2,'modbus_type':'ci','length':1,'read_loc':1,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
            {'id':'8','name':'TEMP_SETTING','label':'溫度設定','unit':'℃','gateway_id':1,'device_id':2,'modbus_type':'hr','length':2,'read_loc':280,'write_loc':280,'calibration':'IEEE754','enabled':True,'controllable':True,},
            {'id':'9','name':'PID_P','label':'比例','unit':'','gateway_id':1,'device_id':2,'modbus_type':'hr','length':1,'read_loc':41,'write_loc':41,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'10','name':'PID_I','label':'積分','unit':'','gateway_id':1,'device_id':2,'modbus_type':'hr','length':1,'read_loc':42,'write_loc':42,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'11','name':'PID_D','label':'微分','unit':'','gateway_id':1,'device_id':2,'modbus_type':'hr','length':1,'read_loc':43,'write_loc':43,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'12','name':'SPEED_MAX','label':'轉速最大值','unit':'','gateway_id':1,'device_id':2,'modbus_type':'hr','length':1,'read_loc':94,'write_loc':94,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'13','name':'SPEED_MIN','label':'轉速最小值','unit':'','gateway_id':1,'device_id':2,'modbus_type':'hr','length':1,'read_loc':93,'write_loc':93,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'14','name':'VII_AB','label':'電壓_ab','unit':'V','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':105,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'15','name':'VII_BC','label':'電壓_bc','unit':'V','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':107,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'16','name':'VII_CA','label':'電壓_ca','unit':'V','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':109,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'17','name':'VII_AVG','label':'電壓_平均','unit':'V','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':111,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'18','name':'I_A','label':'電流_a','unit':'A','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':113,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'19','name':'I_B','label':'電流_b','unit':'A','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':115,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'20','name':'I_C','label':'電流_c','unit':'A','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':117,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'21','name':'I_AVG','label':'電流_平均','unit':'A','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':119,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'22','name':'FREQUENCY','label':'頻率','unit':'','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':121,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'23','name':'KW_A','label':'千瓦_a','unit':'KW','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':123,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'24','name':'KW_B','label':'千瓦_b','unit':'KW','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':125,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'25','name':'KW_C','label':'千瓦_c','unit':'KW','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':127,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'26','name':'KW_TOT','label':'千瓦_平均','unit':'KW','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':129,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'27','name':'POWER_FACTOR','label':'功率因素','unit':'PF','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':147,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'28','name':'KWH','label':'千瓦小時','unit':'KWH','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':149,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'29','name':'DEMAND_KW','label':'千瓦_需量','unit':'KW','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':157,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'30','name':'DEMAND_REMAIN_TIME','label':'','unit':'','gateway_id':1,'device_id':3,'modbus_type':'hr','length':1,'read_loc':159,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
            {'id':'31','name':'DEMAND_KW_MAX','label':'最大千瓦需量','unit':'KW','gateway_id':1,'device_id':3,'modbus_type':'hr','length':2,'read_loc':167,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'32','name':'DEMAND_KW_MAX_YEAR','label':'最大千瓦需量_年','unit':'Year','gateway_id':1,'device_id':3,'modbus_type':'hr','length':1,'read_loc':169,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'33','name':'DEMAND_KW_MAX_MONTH','label':'最大千瓦需量_月','unit':'Month','gateway_id':1,'device_id':3,'modbus_type':'hr','length':1,'read_loc':170,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'34','name':'DEMAND_KW_MAX_DATE','label':'最大千瓦需量_日','unit':'Date','gateway_id':1,'device_id':3,'modbus_type':'hr','length':1,'read_loc':171,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'35','name':'DEMAND_KW_MAX_HOUR','label':'最大千瓦需量_時','unit':'Hour','gateway_id':1,'device_id':3,'modbus_type':'hr','length':1,'read_loc':172,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'36','name':'DEMAND_KW_MAX_MIN','label':'最大千瓦需量_分','unit':'Min','gateway_id':1,'device_id':3,'modbus_type':'hr','length':1,'read_loc':173,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'37','name':'DEMAND_KW_MAX_SECOND','label':'最大千瓦需量_秒','unit':'Second','gateway_id':1,'device_id':3,'modbus_type':'hr','length':1,'read_loc':174,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'38','name':'WATER_VOLUME','label':'水量','unit':'m3','gateway_id':1,'device_id':4,'modbus_type':'hr','length':2,'read_loc':333,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'39','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':1,'device_id':5,'modbus_type':'hr','length':1,'read_loc':251,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'40','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':1,'device_id':5,'modbus_type':'hr','length':1,'read_loc':252,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'41','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':1,'device_id':6,'modbus_type':'hr','length':1,'read_loc':253,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'42','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':1,'device_id':6,'modbus_type':'hr','length':1,'read_loc':254,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'43','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':1,'device_id':7,'modbus_type':'hr','length':1,'read_loc':253,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'44','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':1,'device_id':7,'modbus_type':'hr','length':1,'read_loc':254,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'45','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':1,'device_id':8,'modbus_type':'hr','length':1,'read_loc':253,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'46','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':1,'device_id':8,'modbus_type':'hr','length':1,'read_loc':254,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'47','name':'AUTO_SWITCH','label':'手自動開關','unit':'','gateway_id':1,'device_id':9,'modbus_type':'ci','length':1,'read_loc':1000,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
            {'id':'48','name':'CURRENT_1','label':'電流_1','unit':'A','gateway_id':2,'device_id':10,'modbus_type':'hr','length':1,'read_loc':341,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'49','name':'CURRENT_2','label':'電流_2','unit':'A','gateway_id':2,'device_id':10,'modbus_type':'hr','length':1,'read_loc':342,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'50','name':'CURRENT_3','label':'電流_3','unit':'A','gateway_id':2,'device_id':10,'modbus_type':'hr','length':1,'read_loc':343,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'51','name':'RPM_SETTING','label':'轉速設定','unit':'%','gateway_id':2,'device_id':10,'modbus_type':'hr','length':2,'read_loc':286,'write_loc':286,'calibration':'IEEE754','enabled':True,'controllable':True,},
            {'id':'52','name':'POWER','label':'開關','unit':'','gateway_id':2,'device_id':10,'modbus_type':'ci','length':1,'read_loc':0,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
            {'id':'53','name':'RPM','label':'轉速','unit':'%','gateway_id':2,'device_id':10,'modbus_type':'hr','length':2,'read_loc':261,'write_loc':None,'calibration':'FAN','enabled':True,'controllable':False,},
            {'id':'54','name':'POWER','label':'開關','unit':'','gateway_id':2,'device_id':11,'modbus_type':'ci','length':1,'read_loc':1,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
            {'id':'55','name':'TEMP_SETTING','label':'溫度設定','unit':'℃','gateway_id':2,'device_id':11,'modbus_type':'hr','length':2,'read_loc':280,'write_loc':280,'calibration':'IEEE754','enabled':True,'controllable':True,},
            {'id':'56','name':'PID_P','label':'比例','unit':'','gateway_id':2,'device_id':11,'modbus_type':'hr','length':1,'read_loc':41,'write_loc':41,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'57','name':'PID_I','label':'積分','unit':'','gateway_id':2,'device_id':11,'modbus_type':'hr','length':1,'read_loc':42,'write_loc':42,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'58','name':'PID_D','label':'微分','unit':'','gateway_id':2,'device_id':11,'modbus_type':'hr','length':1,'read_loc':43,'write_loc':43,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'59','name':'SPEED_MAX','label':'轉速最大值','unit':'','gateway_id':2,'device_id':11,'modbus_type':'hr','length':1,'read_loc':94,'write_loc':94,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'60','name':'SPEED_MIN','label':'轉速最小值','unit':'','gateway_id':2,'device_id':11,'modbus_type':'hr','length':1,'read_loc':93,'write_loc':93,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'61','name':'VII_AB','label':'電壓_ab','unit':'V','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':105,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'62','name':'VII_BC','label':'電壓_bc','unit':'V','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':107,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'63','name':'VII_CA','label':'電壓_ca','unit':'V','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':109,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'64','name':'VII_AVG','label':'電壓_平均','unit':'V','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':111,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'65','name':'I_A','label':'電流_a','unit':'A','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':113,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'66','name':'I_B','label':'電流_b','unit':'A','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':115,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'67','name':'I_C','label':'電流_c','unit':'A','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':117,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'68','name':'I_AVG','label':'電流_平均','unit':'A','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':119,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'69','name':'FREQUENCY','label':'頻率','unit':'','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':121,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'70','name':'KW_A','label':'千瓦_a','unit':'KW','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':123,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'71','name':'KW_B','label':'千瓦_b','unit':'KW','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':125,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'72','name':'KW_C','label':'千瓦_c','unit':'KW','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':127,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'73','name':'KW_TOT','label':'千瓦_平均','unit':'KW','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':129,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'74','name':'POWER_FACTOR','label':'功率因素','unit':'PF','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':147,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'75','name':'KWH','label':'千瓦小時','unit':'KWH','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':149,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'76','name':'DEMAND_KW','label':'千瓦_需量','unit':'KW','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':157,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'77','name':'DEMAND_REMAIN_TIME','label':'','unit':'','gateway_id':2,'device_id':12,'modbus_type':'hr','length':1,'read_loc':159,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
            {'id':'78','name':'DEMAND_KW_MAX','label':'最大千瓦需量','unit':'KW','gateway_id':2,'device_id':12,'modbus_type':'hr','length':2,'read_loc':167,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'79','name':'DEMAND_KW_MAX_YEAR','label':'最大千瓦需量_年','unit':'Year','gateway_id':2,'device_id':12,'modbus_type':'hr','length':1,'read_loc':169,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'80','name':'DEMAND_KW_MAX_MONTH','label':'最大千瓦需量_月','unit':'Month','gateway_id':2,'device_id':12,'modbus_type':'hr','length':1,'read_loc':170,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'81','name':'DEMAND_KW_MAX_DATE','label':'最大千瓦需量_日','unit':'Date','gateway_id':2,'device_id':12,'modbus_type':'hr','length':1,'read_loc':171,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'82','name':'DEMAND_KW_MAX_HOUR','label':'最大千瓦需量_時','unit':'Hour','gateway_id':2,'device_id':12,'modbus_type':'hr','length':1,'read_loc':172,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'83','name':'DEMAND_KW_MAX_MIN','label':'最大千瓦需量_分','unit':'Min','gateway_id':2,'device_id':12,'modbus_type':'hr','length':1,'read_loc':173,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'84','name':'DEMAND_KW_MAX_SECOND','label':'最大千瓦需量_秒','unit':'Second','gateway_id':2,'device_id':12,'modbus_type':'hr','length':1,'read_loc':174,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'85','name':'WATER_VOLUME','label':'水量','unit':'m3','gateway_id':2,'device_id':13,'modbus_type':'hr','length':2,'read_loc':333,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'86','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':2,'device_id':14,'modbus_type':'hr','length':1,'read_loc':251,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'87','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':2,'device_id':14,'modbus_type':'hr','length':1,'read_loc':252,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'88','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':2,'device_id':15,'modbus_type':'hr','length':1,'read_loc':253,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'89','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':2,'device_id':15,'modbus_type':'hr','length':1,'read_loc':254,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'90','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':2,'device_id':16,'modbus_type':'hr','length':1,'read_loc':253,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'91','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':2,'device_id':16,'modbus_type':'hr','length':1,'read_loc':254,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'92','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':2,'device_id':17,'modbus_type':'hr','length':1,'read_loc':253,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'93','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':2,'device_id':17,'modbus_type':'hr','length':1,'read_loc':254,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'94','name':'AUTO_SWITCH','label':'手自動開關','unit':'','gateway_id':2,'device_id':18,'modbus_type':'ci','length':1,'read_loc':1000,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
            {'id':'95','name':'CURRENT_1','label':'電流_1','unit':'A','gateway_id':3,'device_id':19,'modbus_type':'hr','length':1,'read_loc':341,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'96','name':'CURRENT_2','label':'電流_2','unit':'A','gateway_id':3,'device_id':19,'modbus_type':'hr','length':1,'read_loc':342,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'97','name':'CURRENT_3','label':'電流_3','unit':'A','gateway_id':3,'device_id':19,'modbus_type':'hr','length':1,'read_loc':343,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'98','name':'RPM_SETTING','label':'轉速設定','unit':'%','gateway_id':3,'device_id':19,'modbus_type':'hr','length':2,'read_loc':286,'write_loc':286,'calibration':'IEEE754','enabled':True,'controllable':True,},
            {'id':'99','name':'POWER','label':'開關','unit':'','gateway_id':3,'device_id':19,'modbus_type':'ci','length':1,'read_loc':0,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
            {'id':'100','name':'RPM','label':'轉速','unit':'%','gateway_id':3,'device_id':19,'modbus_type':'hr','length':2,'read_loc':261,'write_loc':None,'calibration':'FAN','enabled':True,'controllable':False,},
            {'id':'101','name':'POWER','label':'開關','unit':'','gateway_id':3,'device_id':20,'modbus_type':'ci','length':1,'read_loc':1,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
            {'id':'102','name':'TEMP_SETTING','label':'溫度設定','unit':'℃','gateway_id':3,'device_id':20,'modbus_type':'hr','length':2,'read_loc':280,'write_loc':280,'calibration':'IEEE754','enabled':True,'controllable':True,},
            {'id':'103','name':'PID_P','label':'比例','unit':'','gateway_id':3,'device_id':20,'modbus_type':'hr','length':1,'read_loc':41,'write_loc':41,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'104','name':'PID_I','label':'積分','unit':'','gateway_id':3,'device_id':20,'modbus_type':'hr','length':1,'read_loc':42,'write_loc':42,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'105','name':'PID_D','label':'微分','unit':'','gateway_id':3,'device_id':20,'modbus_type':'hr','length':1,'read_loc':43,'write_loc':43,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'106','name':'SPEED_MAX','label':'轉速最大值','unit':'','gateway_id':3,'device_id':20,'modbus_type':'hr','length':1,'read_loc':94,'write_loc':94,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'107','name':'SPEED_MIN','label':'轉速最小值','unit':'','gateway_id':3,'device_id':20,'modbus_type':'hr','length':1,'read_loc':93,'write_loc':93,'calibration':'1','enabled':True,'controllable':True,},
            {'id':'108','name':'VII_AB','label':'電壓_ab','unit':'V','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':105,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'109','name':'VII_BC','label':'電壓_bc','unit':'V','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':107,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'110','name':'VII_CA','label':'電壓_ca','unit':'V','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':109,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'111','name':'VII_AVG','label':'電壓_平均','unit':'V','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':111,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'112','name':'I_A','label':'電流_a','unit':'A','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':113,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'113','name':'I_B','label':'電流_b','unit':'A','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':115,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'114','name':'I_C','label':'電流_c','unit':'A','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':117,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'115','name':'I_AVG','label':'電流_平均','unit':'A','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':119,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'116','name':'FREQUENCY','label':'頻率','unit':'','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':121,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'117','name':'KW_A','label':'千瓦_a','unit':'KW','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':123,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'118','name':'KW_B','label':'千瓦_b','unit':'KW','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':125,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'119','name':'KW_C','label':'千瓦_c','unit':'KW','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':127,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'120','name':'KW_TOT','label':'千瓦_平均','unit':'KW','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':129,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'121','name':'POWER_FACTOR','label':'功率因素','unit':'PF','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':147,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'122','name':'KWH','label':'千瓦小時','unit':'KWH','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':149,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'123','name':'DEMAND_KW','label':'千瓦_需量','unit':'KW','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':157,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'124','name':'DEMAND_REMAIN_TIME','label':'','unit':'','gateway_id':3,'device_id':21,'modbus_type':'hr','length':1,'read_loc':159,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
            {'id':'125','name':'DEMAND_KW_MAX','label':'最大千瓦需量','unit':'KW','gateway_id':3,'device_id':21,'modbus_type':'hr','length':2,'read_loc':167,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'126','name':'DEMAND_KW_MAX_YEAR','label':'最大千瓦需量_年','unit':'Year','gateway_id':3,'device_id':21,'modbus_type':'hr','length':1,'read_loc':169,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'127','name':'DEMAND_KW_MAX_MONTH','label':'最大千瓦需量_月','unit':'Month','gateway_id':3,'device_id':21,'modbus_type':'hr','length':1,'read_loc':170,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'128','name':'DEMAND_KW_MAX_DATE','label':'最大千瓦需量_日','unit':'Date','gateway_id':3,'device_id':21,'modbus_type':'hr','length':1,'read_loc':171,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'129','name':'DEMAND_KW_MAX_HOUR','label':'最大千瓦需量_時','unit':'Hour','gateway_id':3,'device_id':21,'modbus_type':'hr','length':1,'read_loc':172,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'130','name':'DEMAND_KW_MAX_MIN','label':'最大千瓦需量_分','unit':'Min','gateway_id':3,'device_id':21,'modbus_type':'hr','length':1,'read_loc':173,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'131','name':'DEMAND_KW_MAX_SECOND','label':'最大千瓦需量_秒','unit':'Second','gateway_id':3,'device_id':21,'modbus_type':'hr','length':1,'read_loc':174,'write_loc':None,'calibration':'HexToString','enabled':True,'controllable':False,},
            {'id':'132','name':'WATER_VOLUME','label':'水量','unit':'m3','gateway_id':3,'device_id':22,'modbus_type':'hr','length':2,'read_loc':333,'write_loc':None,'calibration':'IEEE754','enabled':True,'controllable':False,},
            {'id':'133','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':3,'device_id':23,'modbus_type':'hr','length':1,'read_loc':251,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'134','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':3,'device_id':23,'modbus_type':'hr','length':1,'read_loc':252,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'135','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':3,'device_id':24,'modbus_type':'hr','length':1,'read_loc':253,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'136','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':3,'device_id':24,'modbus_type':'hr','length':1,'read_loc':254,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'137','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':3,'device_id':25,'modbus_type':'hr','length':1,'read_loc':253,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'138','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':3,'device_id':25,'modbus_type':'hr','length':1,'read_loc':254,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'139','name':'SENSOR_HUMI','label':'濕度','unit':'%','gateway_id':3,'device_id':26,'modbus_type':'hr','length':1,'read_loc':253,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'140','name':'SENSOR_TEMP','label':'溫度','unit':'℃','gateway_id':3,'device_id':26,'modbus_type':'hr','length':1,'read_loc':254,'write_loc':None,'calibration':'0.1','enabled':True,'controllable':False,},
            {'id':'141','name':'AUTO_SWITCH','label':'手自動開關','unit':'','gateway_id':3,'device_id':27,'modbus_type':'ci','length':1,'read_loc':1000,'write_loc':None,'calibration':'1','enabled':True,'controllable':False,},
        ]  
    )

def downgrade():
    op.drop_table('gateway_setting')
    op.drop_table('device_setting')
    op.drop_table('register_setting')
