"""create option

Revision ID: 496e65230508
Revises: a7fa84337187
Create Date: 2024-08-05 08:59:02.679057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '496e65230508'
down_revision = 'a7fa84337187'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    option_table = op.create_table('option',
       sa.Column('id', sa.Integer(), nullable=False),
       sa.Column('name', sa.String(length=255), nullable=True),
       sa.Column('content', sa.Text(), nullable=True),
       sa.PrimaryKeyConstraint('id'),
       sa.UniqueConstraint('name')
    )
    op.bulk_insert(option_table, [
        {'name': 'processCategory', 'content': '[{"id": 1, "category": "In-IJ(\u5ee0\u5167\u6210\u578b)"}, {"id": 2, "category": "Out-IJ(\u59d4\u5916\u6210\u578b)"}, {"id": 3, "category": "In-BE(\u5ee0\u5167\u5f8c\u88fd\u7a0b)"}, {"id": 4, "category": "Out-BE(\u59d4\u5916\u5f8c\u88fd\u7a0b)"}, {"id": 5, "category": "In-TS(\u5ee0\u5167\u51fa\u8ca8\u6aa2\u9a57)"}]'},
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('option')
    # ### end Alembic commands ###
