"""add ts_permissions

Revision ID: 6421d9045265
Revises: b3c9c20b7e01
Create Date: 2023-11-23 08:20:23.841873

"""
import logging
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6421d9045265'
down_revision = 'b3c9c20b7e01'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.add_column(sa.Column("ts_permissions",sa.JSON()))

    user_table = sa.Table("user",
                            sa.MetaData(),
                            sa.Column("id"),
                            sa.Column("role_id"))

    roles_table = sa.Table("roles",
                            sa.MetaData(),
                            sa.Column("id"),
                            sa.Column("ts_permissions", sa.JSON()))
    
    # ts_permissions settings
    # 1. insert roles
    # 2. set relationship by user.role_id
    # 3. update ts_permissions of roles
    try:
        op.bulk_insert(
            roles_table,
            [
                { 'id': 1,
                'name': 'admin'},
            ]
        )
    except:
        #no action when insert conflict
        pass
    op.execute(
        user_table.update()
        .where(user_table.c.id == 1)
        .values({"role_id": 1})
    ) 
    op.execute(
        roles_table.update()
        .where(roles_table.c.id == 1)
        .values({"ts_permissions":{
                    "deviceMonitoring":True,
                    "meterData":True,
                    "waterMeterInformation":True,
                    "parameterSettings":True,
        }})
    ) 
    # ### end Alembic commands ###
    
 
def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('roles', schema=None) as batch_op:
        batch_op.drop_column("ts_permissions")
    # ### end Alembic commands ###
