"""create_LY_0000AB

Revision ID: 66c0c71e597c
Revises: a05d9268c1c9
Create Date: 2024-06-05 07:49:38.079035

"""
import os
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '66c0c71e597c'
down_revision = 'a05d9268c1c9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    LY_ERP_ON = os.getenv("LY_ERP_ON", "False")
    if LY_ERP_ON.lower() != "true":
       return
    op.create_table('ly0000AB',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('MP_NO', sa.String(length=22), nullable=True),
    sa.Column('MP_DATE', sa.DateTime(), nullable=True),
    sa.Column('MP_BDTE', sa.DateTime(), nullable=True),
    sa.Column('MP_EDTE', sa.DateTime(), nullable=True),
    sa.Column('MP_SDTE', sa.DateTime(), nullable=True),
    sa.Column('MP_CTNO', sa.String(length=10), nullable=True),
    sa.Column('MP_CTNM', sa.String(length=60), nullable=True),
    sa.Column('MP_SKNO', sa.String(length=30), nullable=True),
    sa.Column('MP_SKNM', sa.String(length=60), nullable=True),
    sa.Column('MP_RATE_NM', sa.String(length=10), nullable=True),
    sa.Column('MP_RATE', sa.Float(), nullable=True),
    sa.Column('MP_WRNO', sa.String(length=10), nullable=True),
    sa.Column('MP_AQTY', sa.Float(), nullable=True),
    sa.Column('MP_SJTIME', sa.Float(), nullable=True),
    sa.Column('MP_FIM_FLG', sa.String(length=1), nullable=True),
    sa.Column('MP_FINNUM', sa.Float(), nullable=True),
    sa.Column('MP_MAKER', sa.String(length=40), nullable=True),
    sa.Column('MP_CHECK', sa.SmallInteger(), nullable=True),
    sa.Column('MP_CHECKER', sa.String(length=40), nullable=True),
    sa.Column('MP_CHKDTE', sa.DateTime(), nullable=True),
    sa.Column('MP_REM', sa.Text(), nullable=True),
    sa.Column('MP_PH', sa.String(length=30), nullable=True),
    sa.Column('MP_PHNAME', sa.String(length=60), nullable=True),
    sa.Column('MP_WEIGHT', sa.Float(), nullable=True),
    sa.Column('MP_SKDH', sa.String(length=25), nullable=True),
    sa.Column('MP_BZCNO', sa.String(length=30), nullable=True),
    sa.Column('MP_ZCNO', sa.String(length=22), nullable=True),
    sa.Column('MP_UNIT', sa.String(length=8), nullable=True),
    sa.Column('MP_UDEC', sa.Integer(), nullable=True),
    sa.Column('MP_TDEC', sa.Integer(), nullable=True),
    sa.Column('MP_SDEC', sa.Integer(), nullable=True),
    sa.Column('MP_MAENO', sa.String(length=10), nullable=True),
    sa.Column('MP_MAENOC', sa.String(length=10), nullable=True),
    sa.Column('MP_HUNO', sa.String(length=22), nullable=True),
    sa.Column('MP_STDTE', sa.DateTime(), nullable=True),
    sa.Column('MP_WSNO', sa.String(length=10), nullable=True),
    sa.Column('MP_WSNM', sa.String(length=60), nullable=True),
    sa.Column('MP_SPEC', sa.Text(), nullable=True),
    sa.Column('MP_SUMCOST', sa.Float(), nullable=True),
    sa.Column('MP_WKORD', sa.String(length=4), nullable=True),
    sa.Column('MP_WEIGHTTOT', sa.Float(), nullable=True),
    sa.Column('MP_ETDTE', sa.DateTime(), nullable=True),
    sa.Column('MP_NOSW', sa.SmallInteger(), nullable=True),
    sa.Column('MP_HUKIND', sa.String(length=1), nullable=True),
    sa.Column('MP_DPNO', sa.String(length=8), nullable=True),
    sa.Column('MP_PRINT', sa.Integer(), nullable=True),
    sa.Column('MP_CASE', sa.String(length=8), nullable=True),
    sa.Column('MP_FINNUMB', sa.Float(), nullable=True),
    sa.Column('MP_UNFG', sa.SmallInteger(), nullable=True),
    sa.Column('MP_PRICEFG', sa.String(length=1), nullable=True),
    sa.Column('MP_CHECK2', sa.SmallInteger(), nullable=True),
    sa.Column('MP_CHECKER2', sa.String(length=10), nullable=True),
    sa.Column('MP_CHKDTE2', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    LY_ERP_ON = os.getenv("LY_ERP_ON", "False")
    if LY_ERP_ON.lower() != "true":
       return
    op.drop_table('ly0000AB')
    # ### end Alembic commands ###
