"""create production cost analysis

Revision ID: 6727874b76fe
Revises: 0835311ec8f6
Create Date: 2024-11-19 07:53:00.152452

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6727874b76fe'
down_revision = '0835311ec8f6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Create productionScheduleReportView view
    op.execute("""
    CREATE VIEW productionScheduleReportView AS
        SELECT 
            `ps`.`id` AS `productionScheduleId`,
            `ps`.`machineSN` AS `machineSN`,
            `ps`.`workOrderSN` AS `workOrderSN`,
            `ps`.`workOrderQuantity` AS `workOrderQuantity`,
            `ps`.`planOnMachineDate` AS `planOnMachineDate`,
            `ps`.`planFinishDate` AS `planFinishDate`,
            `ps`.`actualOnMachineDate` AS `actualOnMachineDate`,
            `ps`.`status` AS `status`,
            `pr`.`id` AS `productionReportId`,
            `pr`.`serialNumber` AS `serialNumber`,
            `pr`.`lotName` AS `lotName`,
            `pr`.`material` AS `material`,
            `pr`.`productionQuantity` AS `productionQuantity`,
            `pr`.`defectiveQuantity` AS `defectiveQuantity`,
            `pr`.`productionDefectiveRate` AS `productionDefectiveRate`,
            `pr`.`unfinishedQuantity` AS `unfinishedQuantity`,
            `pr`.`colorDifference` AS `colorDifference`,
            `pr`.`deformation` AS `deformation`,
            `pr`.`shrinkage` AS `shrinkage`,
            `pr`.`shortage` AS `shortage`,
            `pr`.`hole` AS `hole`,
            `pr`.`bubble` AS `bubble`,
            `pr`.`impurity` AS `impurity`,
            `pr`.`pressure` AS `pressure`,
            `pr`.`overflow` AS `overflow`,
            `pr`.`flowMark` AS `flowMark`,
            `pr`.`oilStain` AS `oilStain`,
            `pr`.`burr` AS `burr`,
            `pr`.`blackSpot` AS `blackSpot`,
            `pr`.`scratch` AS `scratch`,
            `pr`.`encapsulation` AS `encapsulation`,
            `pr`.`other` AS `other`,
            `pr`.`moldCavity` AS `moldCavity`,
            `pr`.`moldingSecond` AS `moldingSecond`,
            `pr`.`moldModulePerHour` AS `moldModulePerHour`,
            `pr`.`workingHours` AS `workingHours`,
            `pr`.`planProductionQuantity` AS `planProductionQuantity`,
            `pr`.`productionQuantityDifference` AS `productionQuantityDifference`,
            `pr`.`productionYield` AS `productionYield`,
            `pr`.`machineMode` AS `machineMode`,
            `pr`.`machineProductionModule` AS `machineProductionModule`,
            `pr`.`machineProductionQuantity` AS `machineProductionQuantity`,
            `pr`.`machineDefectiveRate` AS `machineDefectiveRate`,
            `pr`.`utilizationRate` AS `utilizationRate`,
            `pr`.`productionEfficiency` AS `productionEfficiency`,
            `pr`.`OEE` AS `OEE`,
            `pr`.`leader` AS `leader`,
            `pr`.`operator1` AS `operator1`,
            `pr`.`operator2` AS `operator2`,
            `pr`.`startTime` AS `startTime`,
            `pr`.`endTime` AS `endTime`,
            `pr`.`comment` AS `comment`,
            `p`.`productSN` AS `productSN`,
            `p`.`productName` AS `productName`,
            `po`.`id` AS `processOptionId`,
            `po`.`processName` AS `processName`,
            `pm`.`processId` AS `processId`,
            GROUP_CONCAT(`lmm`.`moldno` separator ',') AS `moldNos` 
        FROM 
            `productionSchedule` `ps` LEFT JOIN `productionReport` `pr` ON (`ps`.`id` = `pr`.`pschedule_id`)
            LEFT JOIN `product` `p` ON (`ps`.`productId` = `p`.`id`) 
            LEFT JOIN `process` `proc` ON (`ps`.`processId` = `proc`.`id`) 
            LEFT JOIN `processOption` `po` ON (`proc`.`processOptionId` = `po`.`id`)
            LEFT JOIN `processMold` `pm` ON (`proc`.`id` = `pm`.`processId`) 
            LEFT JOIN `ltmoldmap` `lmm` ON (`pm`.`ltmoldmapId` = `lmm`.`no`) 
        WHERE 
            `ps`.`status` <> '取消生產' 
            AND `ps`.`planOnMachineDate` > current_timestamp() - interval 6 month 
        GROUP BY 
            `pr`.`id` 
        ORDER BY 
            `ps`.`id` DESC,
            `pr`.`id`
    """)

    # Create productionCost table
    op.create_table('productionCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productionReportId', sa.Integer(), nullable=True, comment='生產報告ID'),
    sa.Column('unitProductRevenue', sa.Float(), nullable=True, comment='單位產品收益。「單位產品收益」=【廠內報價】中的「實際報價」由「產品編號」對應「實際報價」'),
    sa.Column('fixedUnitProductCost', sa.Float(), nullable=True, comment='固定單位產品成本。「固定單位產品成本」=【廠內報價】中的「總成本」由「產品編號」對應「總成本」'),
    sa.Column('variableUnitProductDefectRate', sa.Float(), nullable=True, comment='變動單位產品不良率。「變動單位產品不良率」=【廠內報價中的原物料費用計算的參數】中的「預估不良率」'),
    sa.Column('variableUnitProductCost', sa.Float(), nullable=True, comment='變動單位產品成本（設定之20%不良率）。「變動單位產品不良成本」=「變動單位產品不良率」*「固定單位產品成本」'),
    sa.Column('totalUnitProductCost', sa.Float(), nullable=True, comment='單位產品總成本。「單位產品總成本」= 「固定單位產品成本」+「變動單位產品不良成本」'),
    sa.Column('totalRevenue', sa.Float(), nullable=True, comment='總收益'),
    sa.Column('targetTotalCost', sa.Float(), nullable=True, comment='目標總成本（含設定之20%不良率）'),
    sa.Column('targetOperatingProfit', sa.Float(), nullable=True, comment='目標營業利益'),
    sa.Column('targetOperatingProfitMargin', sa.Float(), nullable=True, comment='目標營業利益率'),
    sa.Column('maximumDefectQuantity', sa.Float(), nullable=True, comment='生產不良極限數量，超過就賠錢（20%不良＋超過的不良）。「生產不良極限數」=(「總收益」-(「製令數量」*「固定單立產品成本」))/ 「固定單立產品成本」'),
    sa.Column('breakevenTotalQuantity', sa.Float(), nullable=True, comment='損益平衡總數量(良品數＋不良品數）。「損益平衝總數量」=「製令數量」+「生產不良極限數」'),
    sa.Column('breakevenDefectRate', sa.Float(), nullable=True, comment='損益平衡不良率。「損益平衝不良率」= 「生產不良極限數」/ 「損益平衝總數量」'),
    sa.Column('riskControlAlertDefectRate', sa.Float(), nullable=True, comment='風控警示不良率(原始設定不良率的一半）。「風控警示不良率」= 「變動單位產品不良率」/2'),
    sa.Column('actualDefectRate', sa.Float(), nullable=True, comment='實際不良率'),
    sa.Column('yieldRateDifferenceAnalysis', sa.Float(), nullable=True, comment='良率差異分析（預設不良率-實際不良率）。「良率差異分析」=「變動單位產品不良成本」-「實際不良率」'),
    sa.Column('totalProductionQuantity', sa.Float(), nullable=True, comment='總生產數量'),
    sa.Column('totalProductionCost', sa.Float(), nullable=True, comment='總生產成本。「總生產成本」=「固定單位產品成本」* 「總生產數量」'),
    sa.Column('operatingProfit', sa.Float(), nullable=True, comment='營業利益。「營業利益」=「總收益」- 「總生產成本」'),
    sa.Column('operatingProfitMargin', sa.Float(), nullable=True, comment='營業利益率。「營業利益率」= 「營業利益」/ 「總收益」'),
    sa.Column('operatingProfitDifferenceAnalysis', sa.Float(), nullable=True, comment='營業利益差異分析。「營業利益差異分析」=「目標營業利益」-「營業利益」'),
    sa.Column('operatingProfitVariationRate', sa.Float(), nullable=True, comment='營業利益變異率。「營業利益變異率」=「目標營業利益」/「營業利益差異分析」'),
    sa.Column('type', sa.String(length=255), nullable=True, comment='紀錄的類型。即時：real-time，最終：final'),
    sa.Column('logTime', sa.TIMESTAMP(), nullable=True, comment='寫入資料的時間'),
    sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP VIEW productionScheduleReportView")
    op.drop_table('productionCost')
    # ### end Alembic commands ###
