"""create_smartScheduling_related_tables

Revision ID: 67d52448d1fc
Revises: 0cdc20b0c74c
Create Date: 2025-02-25 02:22:01.933839

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData, Table
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '67d52448d1fc'
down_revision = '0cdc20b0c74c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('machineStatus',
    sa.Column('id', sa.Integer(), nullable=False, comment='機台狀態資料表ID'),
    sa.Column('machineId', sa.Integer(), nullable=True, comment='機台ID'),
    sa.Column('planStartDate', sa.DateTime(), nullable=True, comment='預計開始日期'),
    sa.Column('planEndDate', sa.DateTime(), nullable=True, comment='預計結束日期'),
    sa.Column('actualStartDate', sa.DateTime(), nullable=True, comment='實際開始日期'),
    sa.Column('actualEndDate', sa.DateTime(), nullable=True, comment='實際結束日期'),
    sa.Column('status', sa.String(length=255), nullable=True, comment='機台狀態'),
    sa.Column('reason', sa.String(length=255), nullable=True, comment='停機原因'),
    sa.Column('product', sa.String(length=255), nullable=True, comment='試模產品'),
    sa.PrimaryKeyConstraint('id'),
    comment='機台狀態紀錄'
    )

    # Insert Option Data
    connection = op.get_bind()
    metadata = MetaData()
    metadata.reflect(bind=connection)
    option_table = Table('option', metadata, autoload_with=connection)
    op.bulk_insert(option_table, [
        {
            'name': 'machineStatus',
            'content': ('[{"id": 1, "name": "生產中", "schema": "RUN"},'
                        '{"id": 2, "name": "待機中", "schema": "IDLE"},'
                        '{"id": 3, "name": "上模與調機", "schema": "TUNING"},'
                        '{"id": 4, "name": "產品試模", "schema": "TESTING"},'
                        '{"id": 5, "name": "機台停機", "schema": "OFFLINE"}]')
        }
    ])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('machineStatus')
    op.execute("DELETE FROM option WHERE name='machineStatus'")
    # ### end Alembic commands ###
