"""productionSchedule

Revision ID: 827c9ce3b3fd
Revises: abf1d38f6c6b
Create Date: 2023-12-21 06:15:39.032974

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '827c9ce3b3fd'
down_revision = 'abf1d38f6c6b'
branch_labels = None
depends_on = None
"""
    __tablename__ = "productionSchedule"
    id = Column(db.Integer , primary_key = True)
    productionArea = Column(db.String(200))
    machineSN = Column(db.String(200))
    serialNumber = Column(db.Integer)
    workOrderSN = Column(db.String(200))
    productSN = Column(db.String(200))
    productName = Column(db.String(200))
    workOrderQuantity = Column(db.Integer)
    workOrderDate = Column(db.Date)
    moldingSecond = Column(db.Integer)
    #每小時產能
    hourlyCapacity = Column(db.Integer)
    #每日產能
    dailyCapacity = Column(db.Integer)
    planOnMachineDate = Column(db.Date)
    actualOnMachineDate = Column(db.Date, nullable=True)
    moldWorkDays = Column(db.Integer)
    workDays = Column(db.Integer)
    #預計完工日
    planFinishDate = Column(db.Date)
    actualFinishDate = Column(db.Date, nullable=True)
    comment = Column(db.Text, nullable=True)
    dailyWorkingHours = Column(db.Integer)
    moldCavity = Column(db.Integer)
    #週數
    week = Column(db.Integer)
    singleOrDoubleColor = Column(db.String(20))
    conversionRate = Column(db.Float)
    status = Column(db.String(20))

    calculation by functions:
    hourlyCapacity = (60 * 60) * (1/moldingSecond) * moldCavity
    dailyCapacity = hourlyCapacity * dailyWorkingHours * conversionRate
    workDays = workOrderQuantity / dailyCapacity
    week = workOrderDate.isocalendar()[1]
    planFinishDate = workOrderDate + datetime.timedelta(days=workDays+moldWorkDays)
"""


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    metadata = sa.MetaData()
    # seq_autoinc = sa.Sequence('seq_autoinc', metadata=metadata)
    productionSchedule_table = op.create_table('productionSchedule',
       sa.Column('id', sa.Integer(), nullable=False),
       sa.Column('productionArea', sa.String(length=255), nullable=False),
       sa.Column('machineSN', sa.String(length=255), nullable=False),
       sa.Column('serialNumber', sa.String(length=255), nullable=True),
       sa.Column('workOrderSN', sa.String(length=255), nullable=False),
       sa.Column('productSN', sa.String(length=255), nullable=False),
       sa.Column('productName', sa.String(length=255), nullable=False),
       sa.Column('workOrderQuantity', sa.Integer(), nullable=False),
       sa.Column('workOrderDate', sa.Date(), nullable=False),
       sa.Column('moldingSecond', sa.Integer(), nullable=False),
       sa.Column('hourlyCapacity', sa.Integer(), nullable=False),
       sa.Column('dailyCapacity', sa.Integer(), nullable=False),
       sa.Column('planOnMachineDate', sa.Date(), nullable=False),
       sa.Column('actualOnMachineDate', sa.Date(), nullable=True),
       sa.Column('moldWorkDays', sa.Integer(), nullable=False),
       sa.Column('workDays', sa.Integer(), nullable=False),
       sa.Column('planFinishDate', sa.Date(), nullable=False),
       sa.Column('actualFinishDate', sa.Date(), nullable=True),
       sa.Column('comment', sa.Text(), nullable=True),
       sa.Column('dailyWorkingHours', sa.Integer(), nullable=False),
       sa.Column('moldCavity', sa.Integer(), nullable=False),
       sa.Column('week', sa.Integer(), nullable=False),
       sa.Column('singleOrDoubleColor', sa.String(length=255), nullable=False),
       sa.Column('conversionRate', sa.Float(), nullable=False),
       sa.Column('status', sa.String(length=255), nullable=False),
       sa.PrimaryKeyConstraint('id')
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('productionSchedule')

    # ### end Alembic commands ###
