"""add indexes to tables

Revision ID: 840e160e1cce
Revises: 6727874b76fe
Create Date: 2024-12-12 03:22:17.701482

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '840e160e1cce'
down_revision = '6727874b76fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # add index to ltmoldmap
    op.create_index('idx_ltmoldmap_moldno', 'ltmoldmap', ['moldno'])

    # add index to LY0000AB
    op.create_index('idx_ly0000AB_MP_DATE', 'ly0000AB', ['MP_DATE'])
    op.create_index('idx_ly0000AB_MP_NO', 'ly0000AB', ['MP_NO'])

    # add index to LY0000AODetail
    op.create_index('idx_ly0000AO_detail_SD_NO_SKNO_NAME', 'ly0000AO_detail', ['SD_NO', 'SD_SKNO', 'SD_NAME'])
    op.create_index('idx_ly0000AO_detail_SD_SKNO_NAME', 'ly0000AO_detail', ['SD_SKNO', 'SD_NAME'])

    # add index to productionCost
    op.create_index('idx_productionCost_type_logTime', 'productionCost', ['type', 'logTime'])

    # add index to productionReport
    op.create_index('idx_productionReport_serialNumber_pschedule_id', 'productionReport', ['serialNumber', 'pschedule_id'])

    # add index to productionSchedule
    op.create_index('idx_productionSchedule_query_conditions', 'productionSchedule', 
                    ['status', 'planOnMachineDate', 'planFinishDate', 'machineSN', 'workOrderSN'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_productionSchedule_query_conditions', table_name='productionSchedule')
    op.drop_index('idx_productionReport_serialNumber_pschedule_id', table_name='productionReport')
    op.drop_index('idx_productionCost_type_logTime', table_name='productionCost')
    op.drop_index('idx_ly0000AO_detail_SD_NO_SKNO_NAME', table_name='ly0000AO_detail')
    op.drop_index('idx_ly0000AO_detail_SD_SKNO_NAME', table_name='ly0000AO_detail')
    op.drop_index('idx_ly0000AB_MP_NO', table_name='ly0000AB')
    op.drop_index('idx_ly0000AB_MP_DATE', table_name='ly0000AB')
    op.drop_index('idx_ltmoldmap_moldno', table_name='ltmoldmap')

    # ### end Alembic commands ###
