"""create_productionReport

Revision ID: 90616eb73a55
Revises: 827c9ce3b3fd
Create Date: 2024-04-01 02:07:28.290057

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '90616eb73a55'
down_revision = '827c9ce3b3fd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('productionReport',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('startTime', sa.Integer(), nullable=True),
    sa.Column('machineSN', sa.String(length=255), nullable=True),
    sa.Column('workOrderSN', sa.String(length=255), nullable=True),
    sa.Column('serialNumber', sa.Integer(), nullable=True),
    sa.Column('lotName', sa.String(length=255), nullable=True),
    sa.Column('workOrderQuantity', sa.Integer(), nullable=True),
    sa.Column('material', sa.String(length=255), nullable=True),
    sa.Column('moldCavity', sa.Integer(), nullable=True),
    sa.Column('leader', sa.String(length=255), nullable=True),
    sa.Column('operator1', sa.String(length=255), nullable=True),
    sa.Column('operator2', sa.String(length=255), nullable=True),
    sa.Column('productionQuantity', sa.Integer(), nullable=True),
    sa.Column('unfinishedQuantity', sa.Integer(), nullable=True),
    sa.Column('colorDifference', sa.Integer(), nullable=True),
    sa.Column('deformation', sa.Integer(), nullable=True),
    sa.Column('shrinkage', sa.Integer(), nullable=True),
    sa.Column('shortage', sa.Integer(), nullable=True),
    sa.Column('hole', sa.Integer(), nullable=True),
    sa.Column('bubble', sa.Integer(), nullable=True),
    sa.Column('impurity', sa.Integer(), nullable=True),
    sa.Column('pressure', sa.Integer(), nullable=True),
    sa.Column('overflow', sa.Integer(), nullable=True),
    sa.Column('flowMark', sa.Integer(), nullable=True),
    sa.Column('oilStain', sa.Integer(), nullable=True),
    sa.Column('burr', sa.Integer(), nullable=True),
    sa.Column('blackSpot', sa.Integer(), nullable=True),
    sa.Column('scratch', sa.Integer(), nullable=True),
    sa.Column('encapsulation', sa.Integer(), nullable=True),
    sa.Column('other', sa.Integer(), nullable=True),
    sa.Column('defectiveQuantity', sa.Integer(), nullable=True),
    sa.Column('moldModulePerHour', sa.Integer(), nullable=True),
    sa.Column('moldingSecond', sa.Integer(), nullable=True),
    sa.Column('endTime', sa.Integer(), nullable=True),
    sa.Column('comment', sa.String(length=255), nullable=True),
    sa.Column('workingHours', sa.Float(), nullable=True),
    sa.Column('planProductionQuantity', sa.Integer(), nullable=True),
    sa.Column('productionQuantityDifference', sa.Integer(), nullable=True),
    sa.Column('productionDefectiveRate', sa.Float(), nullable=True),
    sa.Column('productionYield', sa.Float(), nullable=True),
    sa.Column('machineMode', sa.String(length=255), nullable=True),
    sa.Column('machineProductionModule', sa.Integer(), nullable=True),
    sa.Column('machineProductionQuantity', sa.Integer(), nullable=True),
    sa.Column('machineDefectiveRate', sa.Float(), nullable=True),
    sa.Column('utilizationRate', sa.Float(), nullable=True),
    sa.Column('productionEfficiency', sa.Float(), nullable=True),
    sa.Column('OEE', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    

def downgrade():
    op.drop_table('productionReport')
