"""create sales quotation

Revision ID: 9aeaf516cfbe
Revises: bffa4a174a6e
Create Date: 2024-11-05 03:02:32.853506

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy import MetaData, Table
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9aeaf516cfbe'
down_revision = 'bffa4a174a6e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    machine_table = op.create_table('machine',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productionArea', sa.String(length=255), nullable=True, comment='機台區域'),
    sa.Column('machineSN', sa.String(length=255), nullable=True, comment='機台編號'),
    sa.Column('singleOrDoubleColor', sa.String(length=255), nullable=True, comment='單射或雙射'),
    sa.Column('tonnage', sa.String(length=255), nullable=True, comment='噸數'),
    sa.Column('moldTrialCost', sa.Integer(), nullable=True, comment='廠內試模費率 8hr'),
    sa.Column('electricityCostPerSec', sa.Float(), nullable=True, comment='每秒電費'),
    sa.PrimaryKeyConstraint('id'),
    comment='機台資訊'
    )
    # Initail machine data
    op.bulk_insert(machine_table,
        [
            {'productionArea': 'A', 'machineSN': 'A1', 'tonnage': '850T', 'singleOrDoubleColor': '單', 'moldTrialCost': 8300, 'electricityCostPerSec': 0.159},
            {'productionArea': 'A', 'machineSN': 'A2', 'tonnage': '400T', 'singleOrDoubleColor': '單', 'moldTrialCost': 5000, 'electricityCostPerSec': 0.0362},
            {'productionArea': 'A', 'machineSN': 'A3', 'tonnage': '550T', 'singleOrDoubleColor': '單', 'moldTrialCost': 6300, 'electricityCostPerSec': 0.1143},
            {'productionArea': 'A', 'machineSN': 'A4', 'tonnage': '350T', 'singleOrDoubleColor': '單', 'moldTrialCost': 4200, 'electricityCostPerSec': 0.0228},
            {'productionArea': 'A', 'machineSN': 'A5', 'tonnage': '260T', 'singleOrDoubleColor': '單', 'moldTrialCost': 3800, 'electricityCostPerSec': 0.0175},
            {'productionArea': 'A', 'machineSN': 'A6', 'tonnage': '80T', 'singleOrDoubleColor': '單', 'moldTrialCost': 2000, 'electricityCostPerSec': 0.0249},
            {'productionArea': 'A', 'machineSN': 'A7', 'tonnage': '125T', 'singleOrDoubleColor': '單', 'moldTrialCost': 2400, 'electricityCostPerSec': 0.0234},
            {'productionArea': 'A', 'machineSN': 'A8', 'tonnage': '180T', 'singleOrDoubleColor': '單', 'moldTrialCost': 2900, 'electricityCostPerSec': 0.0092},
            {'productionArea': 'A', 'machineSN': 'A9', 'tonnage': '180T', 'singleOrDoubleColor': '單', 'moldTrialCost': 2900, 'electricityCostPerSec': 0.0098},
            {'productionArea': 'A', 'machineSN': 'A10', 'tonnage': '200T', 'singleOrDoubleColor': '單', 'moldTrialCost': 3200, 'electricityCostPerSec': 0.0152},
            {'productionArea': 'B', 'machineSN': 'B1', 'tonnage': '500T', 'singleOrDoubleColor': '單', 'moldTrialCost': 5500, 'electricityCostPerSec': 0.0362},
            {'productionArea': 'B', 'machineSN': 'B2', 'tonnage': '450T', 'singleOrDoubleColor': '雙', 'moldTrialCost': 10000, 'electricityCostPerSec': 0.1991},
            {'productionArea': 'B', 'machineSN': 'B3', 'tonnage': '250T', 'singleOrDoubleColor': '雙', 'moldTrialCost': 6500, 'electricityCostPerSec': 0.0818},
            {'productionArea': 'B', 'machineSN': 'B4', 'tonnage': '230T', 'singleOrDoubleColor': '雙', 'moldTrialCost': 6000, 'electricityCostPerSec': 0.0485},
            {'productionArea': 'B', 'machineSN': 'B5', 'tonnage': '230T', 'singleOrDoubleColor': '雙', 'moldTrialCost': 6000, 'electricityCostPerSec': 0.0467},
            {'productionArea': 'B', 'machineSN': 'B6', 'tonnage': '230T', 'singleOrDoubleColor': '雙', 'moldTrialCost': 6000, 'electricityCostPerSec': 0.0132},
            {'productionArea': 'B', 'machineSN': 'B7', 'tonnage': '230T', 'singleOrDoubleColor': '雙', 'moldTrialCost': 6000, 'electricityCostPerSec': 0.0132},
            {'productionArea': 'B', 'machineSN': 'B8', 'tonnage': '230T', 'singleOrDoubleColor': '雙', 'moldTrialCost': 6000, 'electricityCostPerSec': 0.0132},
            {'productionArea': 'B', 'machineSN': 'B9', 'tonnage': '230T', 'singleOrDoubleColor': '雙', 'moldTrialCost': 6000, 'electricityCostPerSec': 0.0132},
            {'productionArea': 'B', 'machineSN': 'B10', 'tonnage': '230T', 'singleOrDoubleColor': '雙', 'moldTrialCost': 6000, 'electricityCostPerSec': 0.0132},
            {'productionArea': 'B', 'machineSN': 'B11', 'tonnage': '180T', 'singleOrDoubleColor': '單', 'moldTrialCost': 3000, 'electricityCostPerSec': 0.0092},
            {'productionArea': 'C', 'machineSN': 'C1', 'tonnage': '550T', 'singleOrDoubleColor': '雙', 'moldTrialCost': 12000, 'electricityCostPerSec': 0.1143},
            {'productionArea': 'C', 'machineSN': 'C2', 'tonnage': '450T', 'singleOrDoubleColor': '單', 'moldTrialCost': 5000, 'electricityCostPerSec': 0.1251},
            {'productionArea': 'C', 'machineSN': 'C3', 'tonnage': '350T', 'singleOrDoubleColor': '單', 'moldTrialCost': 4200, 'electricityCostPerSec': 0.1339},
            {'productionArea': 'C', 'machineSN': 'C4', 'tonnage': '400T', 'singleOrDoubleColor': '單', 'moldTrialCost': 5000, 'electricityCostPerSec': 0.1444},
            {'productionArea': 'C', 'machineSN': 'C5', 'tonnage': '210T', 'singleOrDoubleColor': '單', 'moldTrialCost': 3500, 'electricityCostPerSec': 0.0234},
            {'productionArea': 'C', 'machineSN': 'C6', 'tonnage': '320T', 'singleOrDoubleColor': '單', 'moldTrialCost': 4200, 'electricityCostPerSec': 0.0266},
            {'productionArea': 'C', 'machineSN': 'C7', 'tonnage': '320T', 'singleOrDoubleColor': '單', 'moldTrialCost': 4200, 'electricityCostPerSec': 0.0266},
            {'productionArea': 'C', 'machineSN': 'C8', 'tonnage': '600T', 'singleOrDoubleColor': '單', 'moldTrialCost': 6300, 'electricityCostPerSec': 0.0367},
            {'productionArea': 'C', 'machineSN': 'C9', 'tonnage': '450T', 'singleOrDoubleColor': '單', 'moldTrialCost': 5200, 'electricityCostPerSec': 0.0362},
            {'productionArea': 'D', 'machineSN': 'D1', 'tonnage': '180T', 'singleOrDoubleColor': '單', 'moldTrialCost': 2900, 'electricityCostPerSec': 0.0092},
            {'productionArea': 'D', 'machineSN': 'D2', 'tonnage': '150T', 'singleOrDoubleColor': '單', 'moldTrialCost': 2700, 'electricityCostPerSec': 0.0092},
            {'productionArea': 'D', 'machineSN': 'D3', 'tonnage': '140T', 'singleOrDoubleColor': '單', 'moldTrialCost': 2700, 'electricityCostPerSec': 0.0102},
            {'productionArea': 'D', 'machineSN': 'D4', 'tonnage': '120T', 'singleOrDoubleColor': '單', 'moldTrialCost': 2400, 'electricityCostPerSec': 0.0234},
            {'productionArea': 'D', 'machineSN': 'D5', 'tonnage': '80T', 'singleOrDoubleColor': '單', 'moldTrialCost': 2000, 'electricityCostPerSec': 0.0249},
            {'productionArea': 'D', 'machineSN': 'D6', 'tonnage': '450T', 'singleOrDoubleColor': '單', 'moldTrialCost': 5500, 'electricityCostPerSec': 0.0362},
        ]
    )

    op.create_table('salesQuotation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('quotationSN', sa.String(length=255), nullable=True, comment='報價單編號'),
    sa.Column('createDate', sa.TIMESTAMP(), nullable=True, comment='報價單建立日期'),
    sa.Column('customerName', sa.String(length=255), nullable=True, comment='客戶名稱'),
    sa.Column('productName', sa.String(length=255), nullable=True, comment='產品名稱'),
    sa.Column('subtotalCostWithoutOverhead', sa.Float(), nullable=True, comment='成本小計(不含管銷研)'),
    sa.Column('overheadRnd', sa.Float(), nullable=True, comment='管銷研百分比 (short for Overhead & Research and Development Percentage)'),
    sa.Column('profit', sa.Float(), nullable=True, comment='利潤百分比'),
    sa.Column('risk', sa.Float(), nullable=True, comment='風險百分比'),
    sa.Column('annualDiscount', sa.Float(), nullable=True, comment='年降百分比'),
    sa.Column('rebate', sa.Float(), nullable=True, comment='回饋百分比'),
    sa.Column('actualQuotation', sa.Float(), nullable=True, comment='實際報價'),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_salesQuotation_quotationSN', 'quotationSN'),
    sa.Index('idx_salesQuotation_createDate', 'createDate'),
    sa.Index('idx_salesQuotation_customerName', 'customerName'),
    sa.Index('idx_salesQuotation_productName', 'productName'),
    comment='業務報價'
    )

    op.create_table('SQProcess',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesQuotationId', sa.Integer(), nullable=True, comment='對應的報價ID'),
    sa.Column('processOptionId', sa.Integer(), nullable=True, comment='製程選項ID'),
    sa.ForeignKeyConstraint(['processOptionId'], ['processOption.id'], ),
    sa.ForeignKeyConstraint(['salesQuotationId'], ['salesQuotation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_SQProcess_salesQuotationId', 'salesQuotationId'),
    comment='業務報價中的製程資訊'
    )

    op.create_table('SQMaterialCostSetting',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('estimatedDefectRate', sa.Float(), nullable=True, comment='預估不良率 (%)'),
    sa.Column('estimatedMaterialFluctuation', sa.Float(), nullable=True, comment='預估原料波動 (%)'),
    sa.Column('extractionCost', sa.Float(), nullable=True, comment='抽料費用'),
    sa.Column('processingCost', sa.Float(), nullable=True, comment='加工費用'),
    sa.ForeignKeyConstraint(['SQProcessId'], ['SQProcess.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_SQMaterialCostSetting_SQProcessId', 'SQProcessId'),
    comment='業務報價中的原物料費用計算的參數'
    )

    op.create_table('SQMaterialCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('materialOptionId', sa.Integer(), nullable=True, comment='原物料類別'),
    sa.Column('materialSN', sa.String(length=255), nullable=True, comment='物料編碼'),
    sa.Column('materialName', sa.String(length=255), nullable=True, comment='物料名稱'),
    sa.Column('unit', sa.String(length=255), nullable=True, comment='單位 (如公斤、件等)'),
    sa.Column('weight', sa.Float(), nullable=True, comment='重量'),
    sa.Column('unitPrice', sa.Float(), nullable=True, comment='單價'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['SQProcessId'], ['SQProcess.id'], ),
    sa.ForeignKeyConstraint(['materialOptionId'], ['materialOption.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_SQMaterialCostSetting_SQProcessId', 'SQProcessId'),
    comment='業務報價中的原物料費用資訊'
    )

    op.create_table('SQPackagingCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('packagingType', sa.String(length=50), nullable=True, comment='包材種類'),
    sa.Column('materialSN', sa.String(length=255), nullable=True, comment='物料編碼'),
    sa.Column('materialName', sa.String(length=255), nullable=True, comment='物料名稱'),
    sa.Column('unit', sa.String(length=255), nullable=True, comment='單位 (如件、公斤等)'),
    sa.Column('quantity', sa.Float(), nullable=True, comment='數量'),
    sa.Column('capacity', sa.Float(), nullable=True, comment='容量'),
    sa.Column('bagsPerKg', sa.Float(), nullable=True, comment='每公斤幾個袋子'),
    sa.Column('unitPrice', sa.Float(), nullable=True, comment='單價'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['SQProcessId'], ['SQProcess.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_SQMaterialCostSetting_SQProcessId', 'SQProcessId'),
    comment='業務報價中的包材費用資訊'
    )

    op.create_table('SQInjectionMoldingCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('machineId', sa.Integer(), nullable=True, comment='對應的機台ID'),
    sa.Column('workHoursRatio', sa.Float(), nullable=True, comment='工時比例 (%)'),
    sa.Column('defectiveRate', sa.Float(), nullable=True, comment='不良率 (%)'),
    sa.Column('cycleTime', sa.Float(), nullable=True, comment='成型週期 (秒)'),
    sa.Column('packageTime', sa.Float(), nullable=True, comment='灌包工時 (秒)'),
    sa.Column('moldCavity', sa.Integer(), nullable=True, comment='穴數'),
    sa.Column('unitPrice', sa.Float(), nullable=True, comment='單價'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.Column('subTotal', sa.Float(), nullable=True, comment='小計'),
    sa.Column('electricityCost', sa.Float(), nullable=True, comment='電費'),
    sa.ForeignKeyConstraint(['SQProcessId'], ['SQProcess.id'], ),
    sa.ForeignKeyConstraint(['machineId'], ['machine.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_SQMaterialCostSetting_SQProcessId', 'SQProcessId'),
    comment='業務報價中的成型與生產加工費用資訊'
    )

    op.create_table('SQInPostProcessingCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('workSecond', sa.Float(), nullable=True, comment='工時(秒)'),
    sa.Column('unitPrice', sa.Float(), nullable=True, comment='單價'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['SQProcessId'], ['SQProcess.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_SQMaterialCostSetting_SQProcessId', 'SQProcessId'),
    comment='業務報價中的廠內後製程與檢驗費用'
    )

    op.create_table('SQOutPostProcessingCost',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('SQProcessId', sa.Integer(), nullable=False, comment='對應的報價製程ID'),
    sa.Column('unitPrice', sa.Float(), nullable=True, comment='單價'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['SQProcessId'], ['SQProcess.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_SQMaterialCostSetting_SQProcessId', 'SQProcessId'),
    comment='業務報價中的委外後製程與檢驗費用'
    )

    op.create_table('SQFreight',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesQuotationId', sa.Integer(), nullable=True, comment='對應的報價ID'),
    sa.Column('deliveryDistance', sa.Float(), nullable=True, comment='送貨距離 (公里)'),
    sa.Column('driverWorkHours', sa.Float(), nullable=True, comment='司機工時'),
    sa.Column('fuelCostPerKM', sa.Float(), nullable=True, comment='油錢單價 (每公里)'),
    sa.Column('estimatedShipment', sa.Integer(), nullable=True, comment='預估出貨數量'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['salesQuotationId'], ['salesQuotation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_SQMaterialCostSetting_salesQuotationId', 'salesQuotationId'),
    comment='業務報價中的運費'
    )

    op.create_table('SQCustomsDuty',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('salesQuotationId', sa.Integer(), nullable=True, comment='對應的報價ID'),
    sa.Column('feeType', sa.String(length=255), nullable=True, comment='貨運/關稅'),
    sa.Column('freight', sa.Float(), nullable=True, comment='運費'),
    sa.Column('estimatedShipment', sa.Integer(), nullable=True, comment='預估出貨數量'),
    sa.Column('amount', sa.Float(), nullable=True, comment='金額'),
    sa.ForeignKeyConstraint(['salesQuotationId'], ['salesQuotation.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.Index('idx_SQMaterialCostSetting_salesQuotationId', 'salesQuotationId'),
    comment='業務報價中的貨運與關稅'
    )

    # Insert Option Data
    connection = op.get_bind()
    metadata = MetaData()
    metadata.reflect(bind=connection)
    option_table = Table('option', metadata, autoload_with=connection)
    op.bulk_insert(option_table, [
        {
            'name': 'materialUnit',
            'content': ('[{"id": 1, "name": "公克", "schema": "G"},'
                        '{"id": 2, "name": "件", "schema": "PIECE"},'
                        '{"id": 3, "name": "個", "schema": "ITEM"}]')
        },
        {
            'name': 'packagingUnit',
            'content': ('[{"id": 1, "name": "公斤", "schema": "KG"},'
                        '{"id": 2, "name": "磅", "schema": "POUND"},'
                        '{"id": 3, "name": "件", "schema": "PIECE"},'
                        '{"id": 4, "name": "個", "schema": "ITEM"}]')
        }
    ])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('SQMaterialCostSetting')
    op.drop_table('SQMaterialCost')
    op.drop_table('SQPackagingCost')
    op.drop_table('SQInjectionMoldingCost')
    op.drop_table('SQInPostProcessingCost')
    op.drop_table('SQOutPostProcessingCost')
    op.drop_table('SQFreight')
    op.drop_table('SQCustomsDuty')
    op.drop_table('SQProcess')
    op.drop_table('salesQuotation')
    op.drop_table('machine')
    # Delete the inserted option data
    op.execute(
        """
        DELETE FROM `option`
        WHERE `name` = 'materialUnit'
        """
    )
    op.execute(
        """
        DELETE FROM `option`
        WHERE `name` = 'packagingUnit'
        """
    )
    # ### end Alembic commands ###
