"""add_foreignKey_to_productionReport

Revision ID: a05d9268c1c9
Revises: 90616eb73a55
Create Date: 2024-05-30 09:14:01.914294

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a05d9268c1c9'
down_revision = '90616eb73a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productionReport', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pschedule_id', sa.Integer(), nullable=False))
        batch_op.create_foreign_key(None, 'productionSchedule', ['pschedule_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('productionReport', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('pschedule_id')
    # ### end Alembic commands ###
