"""create processMaterial

Revision ID: a7fa84337187
Revises: 26488421d90f
Create Date: 2024-08-05 08:56:39.700914

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a7fa84337187'
down_revision = '26488421d90f'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processMaterial',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('processId', sa.Integer(), nullable=False),
    sa.Column('materialId', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['materialId'], ['material.id'], ),
    sa.ForeignKeyConstraint(['processId'], ['process.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processMaterial')
    ### end Alembic commands ###