"""calendar

Revision ID: abf1d38f6c6b
Revises: 6421d9045265
Create Date: 2023-12-19 03:45:30.657226

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'abf1d38f6c6b'
down_revision = '6421d9045265'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

#     __tablename__ = "calendar"
#     id = Column(db.Integer , primary_key = True)
#     date = Column(db.Date , unique = True, index = True)
#     isHoliday = Column(db.Boolean)
#     chinese = Column(db.String(200), nullable = True)
#     holidayCategory = Column(db.String(200), nullable = True)
#     description = Column(db.String(200), nullable = True)

    calendar_table = op.create_table('calendar',
       sa.Column('id', sa.Integer(), nullable=False),
       sa.Column('date', sa.Date(), nullable=False),
       sa.Column('isHoliday', sa.Boolean(), nullable=False),
       sa.Column('chinese', sa.String(length=200), nullable=True),
       sa.Column('holidayCategory', sa.String(length=200), nullable=True),
       sa.Column('description', sa.String(length=200), nullable=True),
       sa.PrimaryKeyConstraint('id'),
       sa.UniqueConstraint('date'),
       sa.Index('idx_calendar_date', 'date'),
       )
    op.bulk_insert(
        calendar_table, [
              {'id': 1, 'date': '2021-01-01', 'isHoliday': True, 'chinese': '元旦', 'holidayCategory': '國定假日', 'description': '2021年元旦'},
              {'id': 2, 'date': '2021-02-10', 'isHoliday': True, 'chinese': '除夕', 'holidayCategory': '除夕', 'description': '2021年除夕'},
              {'id': 3, 'date': '2021-02-11', 'isHoliday': True, 'chinese': '春節', 'holidayCategory': '國定假日', 'description': '2021年春節'},
              {'id': 4, 'date': '2021-02-12', 'isHoliday': True, 'chinese': '春節', 'holidayCategory': '國定假日', 'description': '2021年春節'},
              {'id': 5, 'date': '2021-02-15', 'isHoliday': True, 'chinese': '春節', 'holidayCategory': '國定假日', 'description': '2021年春節'},
              {'id': 6, 'date': '2021-02-16', 'isHoliday': True, 'chinese': '春節', 'holidayCategory': '國定假日', 'description': '2021年春節'},
              {'id': 7, 'date': '2021-02-17', 'isHoliday': True, 'chinese': '春節', 'holidayCategory': '國定假日', 'description': '2021年春節'},
              {'id': 8, 'date': '2021-02-28', 'isHoliday': True, 'chinese': '和平紀念日', 'holidayCategory': '國定假日', 'description': '2021年和平紀念日'},
              {'id': 9, 'date': '2021-04-02', 'isHoliday': True, 'chinese': '兒童節', 'holidayCategory': '國定假日', 'description': '2021年兒童節'},
              {'id': 10, 'date': '2021-04-03', 'isHoliday': True, 'chinese': '清明節', 'holidayCategory': '國定假日', 'description': '2021年清明節'},
              {'id': 11, 'date': '2021-04-04', 'isHoliday': True, 'chinese': '清明節', 'holidayCategory': '國定假日', 'description': '2021年清明節'},
              {'id': 12, 'date': '2021-04-05', 'isHoliday': True, 'chinese': '清明節', 'holidayCategory': '國定假日', 'description': '2021年清明節'},
              {'id': 13, 'date': '2021-06-14', 'isHoliday': True, 'chinese': '端午節', 'holidayCategory': '國定假日', 'description': '2021年端午節'},
              {'id': 14, 'date': '2021-09-20', 'isHoliday': True, 'chinese': '中秋節', 'holidayCategory': '國定假日', 'description': '2021年中秋節'},
              {'id': 15, 'date': '2021-09-21', 'isHoliday': True, 'chinese': '中秋節', 'holidayCategory': '國定假日', 'description': '2021年中秋節'},
              {'id': 16, 'date': '2021-10-10', 'isHoliday': True, 'chinese': '國慶日', 'holidayCategory': '國定假日', 'description': '2021年國慶日'},
              {'id': 17, 'date': '2021-12-31', 'isHoliday': True, 'chinese': '除夕', 'holidayCategory': '除夕', 'description': '2021年除夕'},
       ]
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('calendar')
    # ### end Alembic commands ###
