"""create_fake_mold

Revision ID: ae9ed106dc67
Revises: 90616eb73a55
Create Date: 2024-04-07 10:19:57.889153

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ae9ed106dc67'
down_revision = '90616eb73a55'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('molds',
       sa.Column('id', sa.Integer(), nullable=False),
       sa.Column('mold_file_no', sa.String(length=255), nullable=False),
       sa.Column('mold_no', sa.String(length=255), nullable=False),
       sa.Column('project_id', sa.Integer(), nullable=False),
       sa.Column('eval_id', sa.Integer(), nullable=True),
       sa.Column('quot_item_id', sa.Integer(), nullable=True),
       sa.Column('customer_id', sa.Integer(), nullable=False),
       sa.Column('dfm_path', sa.String(length=255), nullable=True),
       sa.Column('cad_path', sa.String(length=255), nullable=True),
       sa.Column('pic1', sa.Integer(), nullable=True),
       sa.Column('pic2', sa.Integer(), nullable=True),
       sa.Column('product_name', sa.String(length=255), nullable=True),
       sa.Column('product_no', sa.String(length=255), nullable=True),
       sa.Column('inject_type', sa.String(length=255), nullable=True),
       sa.Column('mold_class', sa.String(length=255), nullable=True),
       sa.Column('mold_type', sa.String(length=255), nullable=True),
       sa.Column('mold_lifetime', sa.String(length=255), nullable=True),
       sa.Column('t0_date', sa.DateTime(), nullable=True),
       sa.Column('mold_size', sa.String(length=255), nullable=True),
       sa.Column('cavity', sa.String(length=255), nullable=True),
       sa.Column('cavity_material', sa.String(length=255), nullable=True),
       sa.Column('mechanism', sa.String(length=255), nullable=True),
       sa.Column('gate_type', sa.String(length=255), nullable=True),
       sa.Column('leadtime', sa.String(length=255), nullable=True),
       sa.Column('mold_qty', sa.Integer(), nullable=True),
       sa.Column('cycle_time', sa.String(length=255), nullable=True),
       sa.Column('part_material', sa.String(length=255), nullable=True),
       sa.Column('part_material2', sa.String(length=255), nullable=True),
       sa.Column('part_weight', sa.Float(), nullable=True),
       sa.Column('part_weight2', sa.Float(), nullable=True),
       sa.Column('part_color', sa.String(length=255), nullable=True),
       sa.Column('part_color2', sa.String(length=255), nullable=True),
       sa.Column('machine_ton', sa.String(length=255), nullable=True),
       sa.Column('surface_treatment', sa.String(length=255), nullable=True),
       sa.Column('shrinkage_rate', sa.String(length=255), nullable=True),
       sa.Column('build_date', sa.DateTime(), nullable=True),
       sa.Column('note', sa.String(length=255), nullable=True),
       sa.Column('is_outsourcing', sa.Boolean(), nullable=True),
       sa.Column('outsourcer', sa.String(length=255), nullable=True),
       sa.Column('is_locked', sa.Boolean(), nullable=True),
       sa.Column('is_valid', sa.Boolean(), nullable=True),
       sa.Column('created_at', sa.DateTime(), nullable=True),
       sa.Column('updated_at', sa.DateTime(), nullable=True),
       sa.Column('is_transfer', sa.Boolean(), nullable=True),
       sa.PrimaryKeyConstraint('id')
       )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
       op.drop_table('molds')
    # ### end Alembic commands ###
