"""adjust_option

Revision ID: bffa4a174a6e
Revises: d68d853ce1bb
Create Date: 2024-09-06 06:00:01.529438

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'bffa4a174a6e'
down_revision = 'd68d853ce1bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # get the existing option table
    option_table = sa.Table(
       'option',
       sa.MetaData(),
       sa.Column('id', sa.Integer, primary_key=True),
       sa.Column('name', sa.String(255)),
       sa.Column('content', sa.Text),
    )
    # Insert default values into the option table
    op.bulk_insert(option_table, [
        {
            'name': 'workOrderStatus',
            'content': ('[{"id": 1, "name": "尚未上機", "schema": "NOT_YET"},'
                        '{"id": 2, "name": "On-going", "schema": "ON_GOING"},'
                        '{"id": 3, "name": "Done", "schema": "DONE"},'
                        '{"id": 4, "name": "暫停生產", "schema": "PAUSE"},'
                        '{"id": 5, "name": "取消生產", "schema": "CANCEL"}]')
        }
    ])

    op.execute(
       """
       UPDATE `option`
       SET `content` = '[{"id": 1, "category": "In-IJ(廠內成型)", "schema": "In_IJ"},'
                     '{"id": 2, "category": "Out-IJ(委外成型)", "schema": "Out_IJ"},'
                     '{"id": 3, "category": "In-BE(廠內後製程)", "schema": "In_BE"},'
                     '{"id": 4, "category": "Out-BE(委外後製程)", "schema": "Out_BE"},'
                     '{"id": 5, "category": "In-TS(廠內出貨檢驗)", "schema": "In_TS"}]'
       WHERE `name` = 'processCategory'
       """
    )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute(
        """
        DELETE FROM `option`
        WHERE `name` = 'workOrderStatus'
        """
    )
    # ### end Alembic commands ###
