"""create_products

Revision ID: c61c115d5c29
Revises: 66c0c71e597c
Create Date: 2024-07-03 03:08:02.061792

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c61c115d5c29'
down_revision = '66c0c71e597c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productSN', sa.String(length=255), nullable=False),
    sa.Column('productName', sa.String(length=255), nullable=False),
    sa.Column('oldProductSN', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('productSN')
    )
    

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('product')
    # ### end Alembic commands ###
