"""convert INT to TIMESTAMP type

Revision ID: c654b2322268
Revises: 1cf62747091c
Create Date: 2024-08-21 07:10:02.912969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c654b2322268'
down_revision = '1cf62747091c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###

    # productionSchedule
    # 1. Add temporary TIMESTAMP columns
    op.add_column('productionSchedule', sa.Column('temp_workOrderDate', sa.TIMESTAMP(), nullable=True))
    op.add_column('productionSchedule', sa.Column('temp_planOnMachineDate', sa.TIMESTAMP(), nullable=True))
    op.add_column('productionSchedule', sa.Column('temp_actualOnMachineDate', sa.TIMESTAMP(), nullable=True))
    op.add_column('productionSchedule', sa.Column('temp_planFinishDate', sa.TIMESTAMP(), nullable=True))
    op.add_column('productionSchedule', sa.Column('temp_actualFinishDate', sa.TIMESTAMP(), nullable=True))
    # 2. Convert INT to TIMESTAMP using raw SQL
    op.execute("""
           UPDATE productionSchedule 
           SET 
           temp_workOrderDate = FROM_UNIXTIME(workOrderDate),
           temp_planOnMachineDate = FROM_UNIXTIME(planOnMachineDate),
           temp_actualOnMachineDate = FROM_UNIXTIME(actualOnMachineDate),
           temp_planFinishDate = FROM_UNIXTIME(planFinishDate),
           temp_actualFinishDate = FROM_UNIXTIME(actualFinishDate);
    """)
    # 3. Drop the old columns
    op.drop_column('productionSchedule', 'workOrderDate')
    op.drop_column('productionSchedule', 'planOnMachineDate')
    op.drop_column('productionSchedule', 'actualOnMachineDate')
    op.drop_column('productionSchedule', 'planFinishDate')
    op.drop_column('productionSchedule', 'actualFinishDate')
    # 4. Rename the temporary columns to the original names
    op.alter_column('productionSchedule', 'temp_workOrderDate', new_column_name='workOrderDate', existing_type=sa.TIMESTAMP())
    op.alter_column('productionSchedule', 'temp_planOnMachineDate', new_column_name='planOnMachineDate', existing_type=sa.TIMESTAMP())
    op.alter_column('productionSchedule', 'temp_actualOnMachineDate', new_column_name='actualOnMachineDate', existing_type=sa.TIMESTAMP())
    op.alter_column('productionSchedule', 'temp_planFinishDate', new_column_name='planFinishDate', existing_type=sa.TIMESTAMP())
    op.alter_column('productionSchedule', 'temp_actualFinishDate', new_column_name='actualFinishDate', existing_type=sa.TIMESTAMP())

    # productionReport
    # 1. Add temporary TIMESTAMP columns
    op.add_column('productionReport', sa.Column('temp_startTime', sa.TIMESTAMP(), nullable=True))
    op.add_column('productionReport', sa.Column('temp_endTime', sa.TIMESTAMP(), nullable=True))
    # 2. Convert INT to TIMESTAMP using raw SQL
    op.execute("""
           UPDATE productionReport 
           SET 
           temp_startTime = FROM_UNIXTIME(startTime),
           temp_endTime = FROM_UNIXTIME(endTime);
    """)
    # 3. Drop the old columns
    op.drop_column('productionReport', 'startTime')
    op.drop_column('productionReport', 'endTime')
    # 4. Rename the temporary columns to the original names
    op.alter_column('productionReport', 'temp_startTime', new_column_name='startTime', existing_type=sa.TIMESTAMP())
    op.alter_column('productionReport', 'temp_endTime', new_column_name='endTime', existing_type=sa.TIMESTAMP())
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # productionSchedule
    # 1. Re-add the old INT columns
    op.add_column('productionSchedule', sa.Column('temp_workOrderDate', sa.Integer(), nullable=True))
    op.add_column('productionSchedule', sa.Column('temp_planOnMachineDate', sa.Integer(), nullable=True))
    op.add_column('productionSchedule', sa.Column('temp_actualOnMachineDate', sa.Integer(), nullable=True))
    op.add_column('productionSchedule', sa.Column('temp_planFinishDate', sa.Integer(), nullable=True))
    op.add_column('productionSchedule', sa.Column('temp_actualFinishDate', sa.Integer(), nullable=True))
    # 2. Convert TIMESTAMP back to INT using raw SQL
    op.execute("""
           UPDATE productionSchedule 
           SET 
           temp_workOrderDate = UNIX_TIMESTAMP(workOrderDate),
           temp_planOnMachineDate = UNIX_TIMESTAMP(planOnMachineDate),
           temp_actualOnMachineDate = UNIX_TIMESTAMP(actualOnMachineDate),
           temp_planFinishDate = UNIX_TIMESTAMP(planFinishDate),
           temp_actualFinishDate = UNIX_TIMESTAMP(actualFinishDate);
    """)
    # 3. Drop the temporary columns
    op.drop_column('productionSchedule', 'workOrderDate')
    op.drop_column('productionSchedule', 'planOnMachineDate')
    op.drop_column('productionSchedule', 'actualOnMachineDate')
    op.drop_column('productionSchedule', 'planFinishDate')
    op.drop_column('productionSchedule', 'actualFinishDate')
    # 4. Rename the temporary columns to the original names
    op.alter_column('productionSchedule', 'temp_workOrderDate', new_column_name='workOrderDate', existing_type=sa.Integer())
    op.alter_column('productionSchedule', 'temp_planOnMachineDate', new_column_name='planOnMachineDate', existing_type=sa.Integer())
    op.alter_column('productionSchedule', 'temp_actualOnMachineDate', new_column_name='actualOnMachineDate', existing_type=sa.Integer())
    op.alter_column('productionSchedule', 'temp_planFinishDate', new_column_name='planFinishDate', existing_type=sa.Integer())
    op.alter_column('productionSchedule', 'temp_actualFinishDate', new_column_name='actualFinishDate', existing_type=sa.Integer())
    

    # productionReport
    # 1. Re-add the old INT columns
    op.add_column('productionReport', sa.Column('temp_startTime', sa.Integer(), nullable=True))
    op.add_column('productionReport', sa.Column('temp_endTime', sa.Integer(), nullable=True))
    # 2. Convert TIMESTAMP back to INT using raw SQL
    op.execute("""
           UPDATE productionReport 
           SET 
           temp_startTime = UNIX_TIMESTAMP(startTime),
           temp_endTime = UNIX_TIMESTAMP(endTime);
    """)
    # 3. Drop the temporary columns
    op.drop_column('productionReport', 'startTime')
    op.drop_column('productionReport', 'endTime')
    # 4. Rename the temporary columns to the original names
    op.alter_column('productionReport', 'temp_startTime', new_column_name='startTime', existing_type=sa.Integer())
    op.alter_column('productionReport', 'temp_endTime', new_column_name='endTime', existing_type=sa.Integer())
    # ### end Alembic commands ###
