"""create_qualityInspection

Revision ID: d68d853ce1bb
Revises: c654b2322268
Create Date: 2024-09-04 02:04:04.023879

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'd68d853ce1bb'
down_revision = 'c654b2322268'
branch_labels = None
depends_on = None


def upgrade():
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('qualityInspection',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('productionScheduleId', sa.Integer(), nullable=False, comment='生產排程ID'),
    sa.Column('inspectionQuantity', sa.Integer(), nullable=True, comment='檢驗數量'),
    sa.Column('goodQuantity', sa.Integer(), nullable=True, comment='良品數量'),
    sa.Column('inspector', sa.String(length=255), nullable=True, comment='檢驗人員'),
    sa.Column('inspectionDate', sa.TIMESTAMP(), nullable=True, comment='檢驗日期'),
    sa.Column('inspectionType', sa.String(length=255), nullable=True, comment='檢驗類型：首件、巡檢'),
    sa.ForeignKeyConstraint(['productionScheduleId'], ['productionSchedule.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    
    # get the existing option table
    option_table = sa.Table(
       'option',
       sa.MetaData(),
       sa.Column('id', sa.Integer, primary_key=True),
       sa.Column('name', sa.String(255)),
       sa.Column('content', sa.Text),
    )
    # Insert default values into the option table
    op.bulk_insert(option_table, [
        {
            'name': 'inspectionType',
            'content': ('[{"id": 1, "name": "首件", "schema": "FIRST"},'
                        '{"id": 2, "name": "巡檢", "schema": "IN_PROCESS"}]')
        }
    ])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('qualityInspection')
    # Delete the inserted option data
    op.execute(
        """
        DELETE FROM `option`
        WHERE `name` = 'inspectionType'
        """
    )
    # ### end Alembic commands ###
