"""create materialOption

Revision ID: dc7f1ac1fe8b
Revises: deb0a96dc059
Create Date: 2024-08-02 09:23:44.669656

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dc7f1ac1fe8b'
down_revision = 'deb0a96dc059'
branch_labels = None
depends_on = None


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('materialOption',
       sa.Column('id', sa.Integer(), nullable=False),
       sa.Column('materialCode', sa.String(length=255), nullable=True),
       sa.Column('materialType', sa.String(length=255), nullable=True),
       sa.PrimaryKeyConstraint('id'),
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('materialOption')
    ### end Alembic commands ###