"""create processOption

Revision ID: deb0a96dc059
Revises: c61c115d5c29
Create Date: 2024-08-02 09:17:22.329969

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'deb0a96dc059'
down_revision = 'c61c115d5c29'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('processOption',
       sa.Column('id', sa.Integer(), nullable=False),
       sa.Column('processCategory', sa.String(length=255), nullable=True),
       sa.Column('processSN', sa.String(length=255), nullable=True),
       sa.Column('processName', sa.String(length=255), nullable=True),
       sa.PrimaryKeyConstraint('id'),


       
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('processOption')
    # ### end Alembic commands ###
