"""Create Devices and Records

Revision ID: f191b44180c1
Revises: 38695ced4b88
Create Date: 2023-07-14 15:30:54.320577

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f191b44180c1'
down_revision = '38695ced4b88'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_history',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('devices', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('devices', sa.JSON(), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('control_history',
    sa.Column('id', mysql.BIGINT(unsigned=True), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('preset', sa.String(length=10), nullable=True),
    sa.Column('actual', sa.String(length=10), nullable=True),
    sa.Column('state', sa.String(length=32), nullable=True),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['device_id'], ['register_setting.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('control_history')
    op.drop_table('devices')
    op.drop_table('device_history')
    # ### end Alembic commands ###
