// Import the centralized API slice
import apiSlice from "../producRecordApiSlice";

// Extend the API slice with material-specific endpoints
export const materialApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Endpoint for fetching materials by product serial number
    getMaterialsByProductSN: builder.query({
      query: (productSN) => ({
        url: `material/?productSN=${productSN}`, // API endpoint path with product serial number
      }),
      providesTags: ["Material"], // Caching tag to optimize performance
    }),

    // Endpoint for fetching all materials
    getMaterials: builder.query({
      query: () => "material/", // API endpoint path
      providesTags: ["Material"], // Caching tag to optimize performance
    }),

    // Endpoint for fetching a material by its ID
    getMaterialById: builder.query({
      query: (id) => ({
        url: `material/?id=${id}`, // API endpoint path with material ID
      }),
      providesTags: ["Material"], // Caching tag to optimize performance
    }),

    // Endpoint for fetching categorized materials
    getCategorizedMaterials: builder.query({
      query: (categorized = true) => ({
        url: `material/?categorized=${categorized}`, // API endpoint path with categorized parameter
      }),
      providesTags: ["Material"], // Caching tag to optimize performance
    }),

    // Endpoint for updating materials
    updateMaterials: builder.mutation({
      query: (materials) => ({
        url: "material/", // API endpoint path
        method: "PUT", // HTTP method for updating
        body: materials, // Request body containing updated material data
      }),
      invalidatesTags: ["Material"], // Invalidate the 'Material' cache after mutation
    }),
  }),
});

// Export hooks generated by the materialApi slice for use in components
export const {
  useGetMaterialsByProductSNQuery,
  useGetMaterialsQuery,
  useGetMaterialByIdQuery,
  useGetCategorizedMaterialsQuery,
  useUpdateMaterialsMutation,
} = materialApi;

export function useMaterialAtions() {
  const [updateMaterials, { isLoading: isUpdating, error: updateError }] =
    useUpdateMaterialsMutation();

  const handleUpdate = async (materials) => {
    try {
      const response = await updateMaterials(materials).unwrap();
      return response;
    } catch (err) {
      console.error("Failed to update Materials:", err);
      throw err;
    }
  };

  return {
    handleUpdate,

    isUpdating,
    updateError,
  };
}
