// Import the centralized API slice
import apiSlice from "../producRecordApiSlice";

// Extend the API slice with option-specific endpoints
export const optionApi = apiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Endpoint for fetching options by name and optional ID
    getOption: builder.query({
      query: ({ name, id }) => ({
        url: `option/${name}`, // API endpoint path with option name
        params: { id }, // Optional query parameter for option ID
      }),
      providesTags: ["Option"], // Caching tag to optimize performance
    }),

    // Endpoint for creating a new option
    createOption: builder.mutation({
      query: ({ name, option }) => ({
        url: `option/${name}`, // API endpoint path with option name
        method: "POST", // HTTP method for creating
        body: option, // Request body containing option data
      }),
      invalidatesTags: ["Option"], // Invalidate the 'Option' cache after mutation
    }),

    // Endpoint for updating an existing option
    updateOption: builder.mutation({
      query: ({ name, option }) => ({
        url: `option/${name}`, // API endpoint path with option name
        method: "PUT", // HTTP method for updating
        body: option, // Request body containing updated option data
      }),
      invalidatesTags: ["Option"], // Invalidate the 'Option' cache after mutation
    }),
  }),
});

// Export hooks generated by the optionApi slice for use in components
export const {
  useGetOptionQuery,
  useCreateOptionMutation,
  useUpdateOptionMutation,
} = optionApi;
