// Import the centralized API slice
import producRecordApiSlice from "../producRecordApiSlice";

/**
 * Extends the API slice with process-specific endpoints.
 */
export const processApi = producRecordApiSlice.injectEndpoints({
  endpoints: (builder) => ({
    /**
     * Fetches processes and their materials by product ID and process category.
     * @param {Object} params - The parameters for the query.
     * @param {string} params.processCategory - The process category.
     * @param {string} params.productId - The product ID.
     * @returns {Object} - The query result.
     */
    getProcessesAndMaterials: builder.query({
      query: ({ productId, processCategory }) => {
        console.log(productId);

        // Ensure productId is always included
        let queryString = `process/?productId=${productId}`;

        // Conditionally add processCategory if it exists
        if (processCategory) {
          queryString += `&processCategory=${processCategory}`;
        }

        return {
          url: queryString,
        };
      },
      providesTags: ["Process"],
    }),

    /**
     * Fetches a single process and its materials by process ID.
     * @param {string} id - The process ID.
     * @returns {Object} - The query result.
     */
    getSingleProcessAndMaterials: builder.query({
      query: (id) => ({
        url: `process/singleProcess/${id}`,
      }),
      providesTags: ["Process"],
    }),

    // Endpoint for fetching processes by ProductSNs
    getProcessByProductSNs: builder.query({
      query: ({ productSNs }) => ({
        url: `process/getProcessByProductSNs/`,
        params: { productSNs }, // Query parameters
      }),
      providesTags: ["Process"], // Caching tag to optimize performance
    }),

    /**
     * Creates a new process and its materials.
     * @param {Object} processData - The process data to create.
     * @returns {Object} - The mutation result.
     */
    createSingleProcessAndMaterials: builder.mutation({
      query: (processData) => ({
        url: "process/",
        method: "POST",
        body: processData,
      }),
      invalidatesTags: ["Process"],
    }),

    /**
     * Updates an existing process and its materials.
     * @param {Object} processData - The process data to update.
     * @returns {Object} - The mutation result.
     */
    updateSingleProcessAndMaterials: builder.mutation({
      query: (processData) => ({
        url: "process/",
        method: "PUT",
        body: processData,
      }),
      invalidatesTags: ["Process"],
    }),

    /**
     * Deletes a process by its ID.
     * @param {string} id - The ID of the process to delete.
     * @returns {Object} - The mutation result.
     */
    deleteProcess: builder.mutation({
      query: (id) => ({
        url: `process/${id}`,
        method: "DELETE",
      }),
      invalidatesTags: ["Process"],
    }),

    /**
     * Checks if a process is editable and deletable by its ID.
     * @param {string} id - The ID of the process to check.
     * @returns {Object} - The query result.
     */
    checkIsEditableIsDeletable: builder.query({
      query: (id) => ({
        url: `process/checkIsEditableIsDeletable/${id}`,
      }),
      providesTags: ["Process"],
    }),
  }),
});

// Export hooks generated by the processApi slice for use in components
export const {
  useGetProcessesAndMaterialsQuery,
  useGetSingleProcessAndMaterialsQuery,
  useGetProcessByProductSNsQuery,
  useCreateSingleProcessAndMaterialsMutation,
  useUpdateSingleProcessAndMaterialsMutation,
  useDeleteProcessMutation,
  useCheckIsEditableIsDeletableQuery,
} = processApi;

/**
 * Custom hook to encapsulate all process actions.
 * @returns {Object} - An object containing all process actions and states.
 */
export function useProcessActions() {
  const [createProcess, { isLoading: isCreating, error: createError }] =
    useCreateSingleProcessAndMaterialsMutation();

  const [updateProcess, { isLoading: isUpdating, error: updateError }] =
    useUpdateSingleProcessAndMaterialsMutation();

  const [deleteProcess, { isLoading: isDeleting, error: deleteError }] =
    useDeleteProcessMutation();

  /**
   * Handles the creation of a new process.
   * @param {Object} processData - The data for the new process.
   * @returns {Promise<Object>} - The response from the API.
   * @throws Will throw an error if the creation fails.
   */
  const handleCreateProcess = async (processData) => {
    try {
      const response = await createProcess(processData).unwrap();
      return response;
    } catch (err) {
      console.error("Failed to create process:", err);
    }
  };

  /**
   * Handles the update of an existing process.
   * @param {Object} processData - The data for the updated process.
   * @returns {Promise<Object>} - The response from the API.
   * @throws Will throw an error if the update fails.
   */
  const handleUpdateProcess = async (processData) => {
    try {
      const response = await updateProcess(processData).unwrap();
      return response;
    } catch (err) {
      console.error("Failed to update process:", err);
      throw err;
    }
  };

  /**
   * Handles the deletion of a process.
   * @param {string} id - The ID of the process to delete.
   * @returns {Promise<Object>} - The response from the API.
   * @throws Will throw an error if the deletion fails.
   */
  const handleDeleteProcess = async (id) => {
    try {
      const response = await deleteProcess(id).unwrap();
      return response;
    } catch (err) {
      console.error("Failed to delete process:", err);
      throw err;
    }
  };

  return {
    handleCreateProcess,
    isCreating,
    createError,
    handleUpdateProcess,
    isUpdating,
    updateError,
    handleDeleteProcess,
    isDeleting,
    deleteError,
  };
}

/**
 * Converts the raw input data to the format required by the API.
 *
 * @param {Object} data - The raw data to be converted.
 * @param {number} data.productId - The ID of the product.
 * @param {number} data.processOptionId - The ID of the process option.
 * @param {string} data.jigSN - The jig serial number.
 * @param {Array<Object>} data.molds - The array of molds data.
 * @param {Array<Object>} data.materials - The array of materials data.
 *
 * @returns {Array<Object>} - An array of formatted process objects ready to be sent to the API.
 */
export function convertToApiFormat({
  productId,
  processOptionId,
  jigSN,
  molds,
  materials,
  dataId,
}) {
  // 檢查並過濾模具數組中的無效值
  const formattedMolds = Array.isArray(molds)
    ? molds
        .filter(
          (mold) =>
            mold.moldno &&
            typeof mold.moldno === "string" &&
            mold.moldno.trim() !== ""
        )
        .map((mold) =>
          mold.id
            ? {
                id: mold.id,
                moldno: mold.moldno,
              }
            : { moldno: mold.moldno }
        )
    : [];

  // 檢查並過濾物料數組中的無效值
  const formattedMaterials = Array.isArray(materials)
    ? materials
        .filter((material) => material.id)
        .map((material) => ({
          id: material.id,
        }))
    : [];

  // 返回一個格式化的對象數組
  return [
    {
      productId: +productId, // 這裡假設 `id` 與 `productId` 相同
      processOptionId,
      jigSN: jigSN.trim(),
      molds: formattedMolds,
      materials: formattedMaterials,
      id: dataId,
    },
  ];
}
