// Import the centralized API slice
import producRecordApiSlice from "../producRecordApiSlice";

// Extend the API slice with process-specific endpoints
export const processApi = producRecordApiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Endpoint for fetching processes and their materials by product ID and process category
    getProcessesAndMaterials: builder.query({
      query: ({ processCategory, productId }) => ({
        url: "process/", // API endpoint path
        params: { processCategory, productId }, // Query parameters
      }),
      providesTags: ["Process"], // Caching tag to optimize performance
    }),

    // Endpoint for fetching a single process and its materials by process ID
    getSingleProcessAndMaterials: builder.query({
      query: (id) => ({
        url: `process/singleProcess/${id}`, // API endpoint path with process ID
      }),
      providesTags: ["Process"], // Caching tag to optimize performance
    }),

    // Endpoint for fetching processes by ProductSNs
    getProcessByProductSNs: builder.query({
      query: ({ productSNs }) => ({
        url: `process/getProcessByProductSNs/`,
        params: { productSNs }, // Query parameters
      }),
      providesTags: ["Process"], // Caching tag to optimize performance
    }),

    // Endpoint for creating a new process and its materials
    createSingleProcessAndMaterials: builder.mutation({
      query: (processData) => ({
        url: "process/", // API endpoint path
        method: "POST", // HTTP method for creating
        body: processData, // Request body containing process data
      }),
      invalidatesTags: ["Process"], // Invalidate the 'Process' cache after mutation
    }),

    // Endpoint for updating an existing process and its materials
    updateSingleProcessAndMaterials: builder.mutation({
      query: (processData) => ({
        url: "process/", // API endpoint path
        method: "PUT", // HTTP method for updating
        body: processData, // Request body containing updated process data
      }),
      invalidatesTags: ["Process"], // Invalidate the 'Process' cache after mutation
    }),

    // Endpoint for deleting a process by its ID
    deleteProcess: builder.mutation({
      query: (id) => ({
        url: `process/${id}`, // API endpoint path with process ID
        method: "DELETE", // HTTP method for deletion
      }),
      invalidatesTags: ["Process"], // Invalidate the 'Process' cache after mutation
    }),
  }),
});

// Export hooks generated by the processApi slice for use in components
export const {
  useGetProcessesAndMaterialsQuery,
  useGetSingleProcessAndMaterialsQuery,
  useGetProcessByProductSNsQuery,
  useCreateSingleProcessAndMaterialsMutation,
  useUpdateSingleProcessAndMaterialsMutation,
  useDeleteProcessMutation,
} = processApi;
