// Import the centralized API slice
import producRecordApiSlice from "../producRecordApiSlice";

// Extend the API slice with product-specific endpoints
export const productApi = producRecordApiSlice.injectEndpoints({
  endpoints: (builder) => ({
    // Endpoint for fetching products with pagination and filtering
    getProductsWithPagination: builder.query({
      query: (params = {}) => ({
        url: "product/", // API endpoint path
        params: Object.fromEntries(
          Object.entries(params).filter(([_, v]) => v !== undefined)
        ), // Filter out undefined parameters
      }),
      providesTags: ["Product"], // Caching tag to optimize performance
    }),

    // Endpoint for updating products
    updateProducts: builder.mutation({
      query: (products) => ({
        url: "product/", // API endpoint path
        method: "PUT", // HTTP method for updating
        body: products, // Request body containing products to update
      }),
      invalidatesTags: ["Product"], // Invalidate the 'Product' cache after mutation
    }),
  }),
});

// Export hooks generated by the productApi slice for use in components
export const { useGetProductsWithPaginationQuery, useUpdateProductsMutation } =
  productApi;
