export const getPigHouseInventoryFormConfig = (
  pigBreeds,
  managers,
  healthStatuses
) => ({
  name: "pigHouseInventory",
  submitText: "提交豬舍庫存",
  fields: [
    {
      name: "name",
      label: "豬舍名稱",
      type: "input",
      span: 12,
      rules: [{ required: true, message: "請輸入豬舍名稱" }],
    },
    {
      name: "pigBreed",
      label: "豬隻品種",
      type: "select",
      span: 12,
      rules: [{ required: true, message: "請選擇豬隻品種" }],
      options: pigBreeds.map((breed) => ({ value: breed, label: breed })),
    },
    {
      name: "currentStock",
      label: "當前存欄量",
      type: "number",
      span: 8,
      rules: [{ required: true, message: "請輸入當前存欄量" }],
      props: { min: 0, style: { width: "100%" } },
    },
    {
      name: "maxCapacity",
      label: "最大容量",
      type: "number",
      span: 8,
      rules: [{ required: true, message: "請輸入最大容量" }],
      props: { min: 0, style: { width: "100%" } },
    },
    {
      name: "avgWeight",
      label: "平均體重 (kg)",
      type: "number",
      span: 8,
      rules: [{ required: true, message: "請輸入平均體重" }],
      props: { min: 0, step: 0.1, style: { width: "100%" } },
    },
    {
      name: "lastUpdated",
      label: "最後更新日期",
      type: "date",
      span: 12,
      rules: [{ required: true, message: "請選擇最後更新日期" }],
      props: { style: { width: "100%" } },
    },
    {
      name: "manager",
      label: "負責人",
      type: "select",
      span: 12,
      rules: [{ required: true, message: "請選擇負責人" }],
      options: managers.map((manager) => ({ value: manager, label: manager })),
    },
    {
      name: "healthStatus",
      label: "健康狀況",
      type: "select",
      span: 24,
      rules: [{ required: true, message: "請選擇健康狀況" }],
      options: healthStatuses.map((status) => ({
        value: status,
        label: status,
      })),
    },
    {
      name: "hasDisease",
      label: "是否有疾病",
      type: "checkbox",
      span: 24,
    },
    {
      name: "diseaseDescription",
      label: "疾病描述",
      type: "textarea",
      span: 24,
      dependencies: ["hasDisease"],
      shouldRender: (formValues) => formValues.hasDisease,
      rules: [{ required: true, message: "請輸入疾病描述" }],
    },
  ],
});
