export const getPigHouseInventoryFormConfig = () => ({
  name: "pigHouseInventory",
  submitText: "提交豬舍庫存",
  id: null,
  fields: [
    {
      name: "date",
      label: "日期",
      type: "date",
      span: 8,
      // rules: [{ required: true, message: "請選擇日期" }],
    },

    {
      name: "totalPigs",
      label: "總豬數",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入總豬數" }],
    },
    {
      name: "totalDeaths",
      label: "總死亡數",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入總死亡數" }],
    },
    {
      name: "totalSold",
      label: "總售出數",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入總售出數" }],
    },

    // 種豬
    {
      name: "breedingOriginal",
      label: "種豬原始數量",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入種豬原始數量" }],
    },
    {
      name: "breedingIn",
      label: "種豬移入",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入種豬移入數量" }],
    },
    {
      name: "breedingOut",
      label: "種豬移出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入種豬移出數量" }],
    },
    {
      name: "breedingDeath",
      label: "種豬死亡",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入種豬死亡數量" }],
    },
    {
      name: "breedingSold",
      label: "種豬售出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入種豬售出數量" }],
    },
    {
      name: "breedingRemaining",
      label: "種豬剩餘",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入種豬剩餘數量" }],
    },

    // 檢定豬
    {
      name: "testingOriginal",
      label: "檢定豬原始數量",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入檢定豬原始數量" }],
    },
    {
      name: "testingIn",
      label: "檢定豬移入",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入檢定豬移入數量" }],
    },
    {
      name: "testingOut",
      label: "檢定豬移出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入檢定豬移出數量" }],
    },
    {
      name: "testingDeath",
      label: "檢定豬死亡",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入檢定豬死亡數量" }],
    },
    {
      name: "testingSold",
      label: "檢定豬售出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入檢定豬售出數量" }],
    },
    {
      name: "testingRemaining",
      label: "檢定豬剩餘",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入檢定豬剩餘數量" }],
    },

    // 肉豬
    {
      name: "meatOriginal",
      label: "肉豬原始數量",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入肉豬原始數量" }],
    },
    {
      name: "meatIn",
      label: "肉豬移入",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入肉豬移入數量" }],
    },
    {
      name: "meatOut",
      label: "肉豬移出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入肉豬移出數量" }],
    },
    {
      name: "meatDeath",
      label: "肉豬死亡",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入肉豬死亡數量" }],
    },
    {
      name: "meatSold",
      label: "肉豬售出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入肉豬售出數量" }],
    },
    {
      name: "meatRemaining",
      label: "肉豬剩餘",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入肉豬剩餘數量" }],
    },

    // 分娩(3)
    {
      name: "farrowing3SowOriginal",
      label: "分娩(3)母豬原始數量",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)母豬原始數量" }],
    },
    {
      name: "farrowing3SowIn",
      label: "分娩(3)母豬移入",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)母豬移入數量" }],
    },
    {
      name: "farrowing3SowOut",
      label: "分娩(3)母豬移出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)母豬移出數量" }],
    },
    {
      name: "farrowing3SowDeath",
      label: "分娩(3)母豬死亡",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)母豬死亡數量" }],
    },
    {
      name: "farrowing3SowSold",
      label: "分娩(3)母豬售出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)母豬售出數量" }],
    },
    {
      name: "farrowing3SowRemaining",
      label: "分娩(3)母豬剩餘",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)母豬剩餘數量" }],
    },
    {
      name: "farrowing3PigletOriginal",
      label: "分娩(3)仔豬原始數量",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)仔豬原始數量" }],
    },
    {
      name: "farrowing3PigletIn",
      label: "分娩(3)仔豬移入",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)仔豬移入數量" }],
    },
    {
      name: "farrowing3PigletOut",
      label: "分娩(3)仔豬移出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)仔豬移出數量" }],
    },
    {
      name: "farrowing3PigletDeath",
      label: "分娩(3)仔豬死亡",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)仔豬死亡數量" }],
    },
    {
      name: "farrowing3PigletSold",
      label: "分娩(3)仔豬售出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)仔豬售出數量" }],
    },
    {
      name: "farrowing3PigletRemaining",
      label: "分娩(3)仔豬剩餘",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)仔豬剩餘數量" }],
    },
    {
      name: "farrowing3PigletBorn",
      label: "分娩(3)仔豬出生",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)仔豬出生數量" }],
    },
    {
      name: "farrowing3PigletWeakBorn",
      label: "分娩(3)仔豬弱仔出生",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)仔豬弱仔出生數量" }],
    },
    {
      name: "farrowing3PigletWeakDeath",
      label: "分娩(3)仔豬弱仔死亡",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(3)仔豬弱仔死亡數量" }],
    },

    // 分娩(8)
    {
      name: "farrowing8SowOriginal",
      label: "分娩(8)母豬原始數量",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)母豬原始數量" }],
    },
    {
      name: "farrowing8SowIn",
      label: "分娩(8)母豬移入",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)母豬移入數量" }],
    },
    {
      name: "farrowing8SowOut",
      label: "分娩(8)母豬移出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)母豬移出數量" }],
    },
    {
      name: "farrowing8SowDeath",
      label: "分娩(8)母豬死亡",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)母豬死亡數量" }],
    },
    {
      name: "farrowing8SowSold",
      label: "分娩(8)母豬售出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)母豬售出數量" }],
    },
    {
      name: "farrowing8SowRemaining",
      label: "分娩(8)母豬剩餘",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)母豬剩餘數量" }],
    },
    {
      name: "farrowing8PigletOriginal",
      label: "分娩(8)仔豬原始數量",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)仔豬原始數量" }],
    },
    {
      name: "farrowing8PigletIn",
      label: "分娩(8)仔豬移入",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)仔豬移入數量" }],
    },
    {
      name: "farrowing8PigletOut",
      label: "分娩(8)仔豬移出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)仔豬移出數量" }],
    },
    {
      name: "farrowing8PigletDeath",
      label: "分娩(8)仔豬死亡",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)仔豬死亡數量" }],
    },
    {
      name: "farrowing8PigletSold",
      label: "分娩(8)仔豬售出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)仔豬售出數量" }],
    },
    {
      name: "farrowing8PigletRemaining",
      label: "分娩(8)仔豬剩餘",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)仔豬剩餘數量" }],
    },
    {
      name: "farrowing8PigletBorn",
      label: "分娩(8)仔豬出生",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)仔豬出生數量" }],
    },
    {
      name: "farrowing8PigletWeakBorn",
      label: "分娩(8)仔豬弱仔出生",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)仔豬弱仔出生數量" }],
    },
    {
      name: "farrowing8PigletWeakDeath",
      label: "分娩(8)仔豬弱仔死亡",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)仔豬弱仔死亡數量" }],
    },
    {
      name: "farrowing8NurseryPigOriginal",
      label: "分娩(8)保育豬原始數量",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)保育豬原始數量" }],
    },
    {
      name: "farrowing8NurseryPigIn",
      label: "分娩(8)保育豬移入",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)保育豬移入數量" }],
    },
    {
      name: "farrowing8NurseryPigOut",
      label: "分娩(8)保育豬移出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)保育豬移出數量" }],
    },
    {
      name: "farrowing8NurseryPigDeath",
      label: "分娩(8)保育豬死亡",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)保育豬死亡數量" }],
    },
    {
      name: "farrowing8NurseryPigSold",
      label: "分娩(8)保育豬售出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)保育豬售出數量" }],
    },
    {
      name: "farrowing8NurseryPigRemaining",
      label: "分娩(8)保育豬剩餘",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)保育豬剩餘數量" }],
    },
    {
      name: "farrowing8Sold",
      label: "分娩(8)售出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入分娩(8)售出數量" }],
    },
    // 保育豬
    {
      name: "nurseryOriginal",
      label: "保育豬原始數量",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入保育豬原始數量" }],
    },
    {
      name: "nurseryIn",
      label: "保育豬移入",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入保育豬移入數量" }],
    },
    {
      name: "nurseryOut",
      label: "保育豬移出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入保育豬移出數量" }],
    },
    {
      name: "nurseryDeath",
      label: "保育豬死亡",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入保育豬死亡數量" }],
    },
    {
      name: "nurserySold",
      label: "保育豬售出",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入保育豬售出數量" }],
    },
    {
      name: "nurseryRemaining",
      label: "保育豬剩餘",
      type: "number",
      span: 8,
      // rules: [{ required: true, message: "請輸入保育豬剩餘數量" }],
    },
  ],
});
